install: gradle wrapper --gradle-version 4.2

dist: xenial

language: java

jdk:
  - oraclejdk8

script:
  - gradle build

after_success:
  - gradle clean test jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
