install:
- |
  sudo apt-get -y install --upgrade gradle
  gradle wrapper --gradle-version 6.0.1

dist: bionic

language: java

jdk:
  - openjdk9

script:
  - gradle build

after_success:
  - gradle clean test jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
