@file:Suppress("unused")

package uk.co.newagedev.knade.math

// Vec2f non-duplicate l-value swizzling xy
inline var Vec2f.xy: Vec2f get() = Vec2f(x, y); set(value) { x = value.x; y = value.y }
inline var Vec2f.yx: Vec2f get() = Vec2f(y, x); set(value) { y = value.x; x = value.y }

// Vec2f duplicate l-value swizzling xy
inline val Vec2f.xx:   Vec2f get() = Vec2f(x, x)
inline val Vec2f.yy:   Vec2f get() = Vec2f(y, y)
inline val Vec2f.yyy:  Vec3f get() = Vec3f(y, y, y)
inline val Vec2f.yyx:  Vec3f get() = Vec3f(y, y, x)
inline val Vec2f.yxy:  Vec3f get() = Vec3f(y, x, y)
inline val Vec2f.yxx:  Vec3f get() = Vec3f(y, x, x)
inline val Vec2f.xyy:  Vec3f get() = Vec3f(x, y, y)
inline val Vec2f.xyx:  Vec3f get() = Vec3f(x, y, x)
inline val Vec2f.xxy:  Vec3f get() = Vec3f(x, x, y)
inline val Vec2f.xxx:  Vec3f get() = Vec3f(x, x, x)
inline val Vec2f.yyyy: Vec4f get() = Vec4f(y, y, y, y)
inline val Vec2f.yyyx: Vec4f get() = Vec4f(y, y, y, x)
inline val Vec2f.yyxy: Vec4f get() = Vec4f(y, y, x, y)
inline val Vec2f.yyxx: Vec4f get() = Vec4f(y, y, x, x)
inline val Vec2f.yxyy: Vec4f get() = Vec4f(y, x, y, y)
inline val Vec2f.yxyx: Vec4f get() = Vec4f(y, x, y, x)
inline val Vec2f.yxxy: Vec4f get() = Vec4f(y, x, x, y)
inline val Vec2f.yxxx: Vec4f get() = Vec4f(y, x, x, x)
inline val Vec2f.xyyy: Vec4f get() = Vec4f(x, y, y, y)
inline val Vec2f.xyyx: Vec4f get() = Vec4f(x, y, y, x)
inline val Vec2f.xyxy: Vec4f get() = Vec4f(x, y, x, y)
inline val Vec2f.xyxx: Vec4f get() = Vec4f(x, y, x, x)
inline val Vec2f.xxyy: Vec4f get() = Vec4f(x, x, y, y)
inline val Vec2f.xxyx: Vec4f get() = Vec4f(x, x, y, x)
inline val Vec2f.xxxy: Vec4f get() = Vec4f(x, x, x, y)
inline val Vec2f.xxxx: Vec4f get() = Vec4f(x, x, x, x)

// Vec3f non-duplicate l-value swizzling xyz
inline var Vec3f.xy:  Vec2f get() = Vec2f(x, y);    set(value) { x = value.x; y = value.y }
inline var Vec3f.yx:  Vec2f get() = Vec2f(y, x);    set(value) { y = value.x; x = value.y }
inline var Vec3f.zy:  Vec2f get() = Vec2f(z, y);    set(value) { z = value.x; y = value.y }
inline var Vec3f.yz:  Vec2f get() = Vec2f(y, z);    set(value) { y = value.x; z = value.y }
inline var Vec3f.xz:  Vec2f get() = Vec2f(x, z);    set(value) { x = value.x; z = value.y }
inline var Vec3f.zx:  Vec2f get() = Vec2f(z, x);    set(value) { z = value.x; x = value.y }
inline var Vec3f.zxy: Vec3f get() = Vec3f(z, x, y); set(value) { z = value.x; x = value.y; y = value.z }
inline var Vec3f.zyx: Vec3f get() = Vec3f(z, y, x); set(value) { z = value.x; y = value.y; x = value.z }
inline var Vec3f.xzy: Vec3f get() = Vec3f(x, z, y); set(value) { x = value.x; z = value.y; y = value.z }
inline var Vec3f.xyz: Vec3f get() = Vec3f(x, y, z); set(value) { x = value.x; y = value.y; z = value.z }
inline var Vec3f.yxz: Vec3f get() = Vec3f(y, x, z); set(value) { y = value.x; x = value.y; z = value.z }
inline var Vec3f.yzx: Vec3f get() = Vec3f(y, z, x); set(value) { y = value.x; z = value.y; x = value.z }

// Vec3f duplicate l-value swizzling xyz
inline val Vec3f.xx:   Vec2f get() = Vec2f(x, x)
inline val Vec3f.yy:   Vec2f get() = Vec2f(y, y)
inline val Vec3f.zz:   Vec2f get() = Vec2f(z, z)
inline val Vec3f.zzz:  Vec3f get() = Vec3f(z, z, z)
inline val Vec3f.zzy:  Vec3f get() = Vec3f(z, z, y)
inline val Vec3f.zzx:  Vec3f get() = Vec3f(z, z, x)
inline val Vec3f.zyz:  Vec3f get() = Vec3f(z, y, z)
inline val Vec3f.zyy:  Vec3f get() = Vec3f(z, y, y)
inline val Vec3f.zxz:  Vec3f get() = Vec3f(z, x, z)
inline val Vec3f.zxx:  Vec3f get() = Vec3f(z, x, x)
inline val Vec3f.yzz:  Vec3f get() = Vec3f(y, z, z)
inline val Vec3f.yzy:  Vec3f get() = Vec3f(y, z, y)
inline val Vec3f.yyz:  Vec3f get() = Vec3f(y, y, z)
inline val Vec3f.yyy:  Vec3f get() = Vec3f(y, y, y)
inline val Vec3f.yyx:  Vec3f get() = Vec3f(y, y, x)
inline val Vec3f.yxy:  Vec3f get() = Vec3f(y, x, y)
inline val Vec3f.yxx:  Vec3f get() = Vec3f(y, x, x)
inline val Vec3f.xzz:  Vec3f get() = Vec3f(x, z, z)
inline val Vec3f.xzx:  Vec3f get() = Vec3f(x, z, x)
inline val Vec3f.xyy:  Vec3f get() = Vec3f(x, y, y)
inline val Vec3f.xyx:  Vec3f get() = Vec3f(x, y, x)
inline val Vec3f.xxz:  Vec3f get() = Vec3f(x, x, z)
inline val Vec3f.xxy:  Vec3f get() = Vec3f(x, x, y)
inline val Vec3f.xxx:  Vec3f get() = Vec3f(x, x, x)
inline val Vec3f.zzzz: Vec4f get() = Vec4f(z, z, z, z)
inline val Vec3f.zzzy: Vec4f get() = Vec4f(z, z, z, y)
inline val Vec3f.zzzx: Vec4f get() = Vec4f(z, z, z, x)
inline val Vec3f.zzyz: Vec4f get() = Vec4f(z, z, y, z)
inline val Vec3f.zzyy: Vec4f get() = Vec4f(z, z, y, y)
inline val Vec3f.zzyx: Vec4f get() = Vec4f(z, z, y, x)
inline val Vec3f.zzxz: Vec4f get() = Vec4f(z, z, x, z)
inline val Vec3f.zzxy: Vec4f get() = Vec4f(z, z, x, y)
inline val Vec3f.zzxx: Vec4f get() = Vec4f(z, z, x, x)
inline val Vec3f.zyzz: Vec4f get() = Vec4f(z, y, z, z)
inline val Vec3f.zyzy: Vec4f get() = Vec4f(z, y, z, y)
inline val Vec3f.zyzx: Vec4f get() = Vec4f(z, y, z, x)
inline val Vec3f.zyyz: Vec4f get() = Vec4f(z, y, y, z)
inline val Vec3f.zyyy: Vec4f get() = Vec4f(z, y, y, y)
inline val Vec3f.zyyx: Vec4f get() = Vec4f(z, y, y, x)
inline val Vec3f.zyxz: Vec4f get() = Vec4f(z, y, x, z)
inline val Vec3f.zyxy: Vec4f get() = Vec4f(z, y, x, y)
inline val Vec3f.zyxx: Vec4f get() = Vec4f(z, y, x, x)
inline val Vec3f.zxzz: Vec4f get() = Vec4f(z, x, z, z)
inline val Vec3f.zxzy: Vec4f get() = Vec4f(z, x, z, y)
inline val Vec3f.zxzx: Vec4f get() = Vec4f(z, x, z, x)
inline val Vec3f.zxyz: Vec4f get() = Vec4f(z, x, y, z)
inline val Vec3f.zxyy: Vec4f get() = Vec4f(z, x, y, y)
inline val Vec3f.zxyx: Vec4f get() = Vec4f(z, x, y, x)
inline val Vec3f.zxxz: Vec4f get() = Vec4f(z, x, x, z)
inline val Vec3f.zxxy: Vec4f get() = Vec4f(z, x, x, y)
inline val Vec3f.zxxx: Vec4f get() = Vec4f(z, x, x, x)
inline val Vec3f.yzzz: Vec4f get() = Vec4f(y, z, z, z)
inline val Vec3f.yzzy: Vec4f get() = Vec4f(y, z, z, y)
inline val Vec3f.yzzx: Vec4f get() = Vec4f(y, z, z, x)
inline val Vec3f.yzyz: Vec4f get() = Vec4f(y, z, y, z)
inline val Vec3f.yzyy: Vec4f get() = Vec4f(y, z, y, y)
inline val Vec3f.yzyx: Vec4f get() = Vec4f(y, z, y, x)
inline val Vec3f.yzxz: Vec4f get() = Vec4f(y, z, x, z)
inline val Vec3f.yzxy: Vec4f get() = Vec4f(y, z, x, y)
inline val Vec3f.yzxx: Vec4f get() = Vec4f(y, z, x, x)
inline val Vec3f.yyzz: Vec4f get() = Vec4f(y, y, z, z)
inline val Vec3f.yyzy: Vec4f get() = Vec4f(y, y, z, y)
inline val Vec3f.yyzx: Vec4f get() = Vec4f(y, y, z, x)
inline val Vec3f.yyyz: Vec4f get() = Vec4f(y, y, y, z)
inline val Vec3f.yyyy: Vec4f get() = Vec4f(y, y, y, y)
inline val Vec3f.yyyx: Vec4f get() = Vec4f(y, y, y, x)
inline val Vec3f.yyxz: Vec4f get() = Vec4f(y, y, x, z)
inline val Vec3f.yyxy: Vec4f get() = Vec4f(y, y, x, y)
inline val Vec3f.yyxx: Vec4f get() = Vec4f(y, y, x, x)
inline val Vec3f.yxzz: Vec4f get() = Vec4f(y, x, z, z)
inline val Vec3f.yxzy: Vec4f get() = Vec4f(y, x, z, y)
inline val Vec3f.yxzx: Vec4f get() = Vec4f(y, x, z, x)
inline val Vec3f.yxyz: Vec4f get() = Vec4f(y, x, y, z)
inline val Vec3f.yxyy: Vec4f get() = Vec4f(y, x, y, y)
inline val Vec3f.yxyx: Vec4f get() = Vec4f(y, x, y, x)
inline val Vec3f.yxxz: Vec4f get() = Vec4f(y, x, x, z)
inline val Vec3f.yxxy: Vec4f get() = Vec4f(y, x, x, y)
inline val Vec3f.yxxx: Vec4f get() = Vec4f(y, x, x, x)
inline val Vec3f.xzzz: Vec4f get() = Vec4f(x, z, z, z)
inline val Vec3f.xzzy: Vec4f get() = Vec4f(x, z, z, y)
inline val Vec3f.xzzx: Vec4f get() = Vec4f(x, z, z, x)
inline val Vec3f.xzyz: Vec4f get() = Vec4f(x, z, y, z)
inline val Vec3f.xzyy: Vec4f get() = Vec4f(x, z, y, y)
inline val Vec3f.xzyx: Vec4f get() = Vec4f(x, z, y, x)
inline val Vec3f.xzxz: Vec4f get() = Vec4f(x, z, x, z)
inline val Vec3f.xzxy: Vec4f get() = Vec4f(x, z, x, y)
inline val Vec3f.xzxx: Vec4f get() = Vec4f(x, z, x, x)
inline val Vec3f.xyzz: Vec4f get() = Vec4f(x, y, z, z)
inline val Vec3f.xyzy: Vec4f get() = Vec4f(x, y, z, y)
inline val Vec3f.xyzx: Vec4f get() = Vec4f(x, y, z, x)
inline val Vec3f.xyyz: Vec4f get() = Vec4f(x, y, y, z)
inline val Vec3f.xyyy: Vec4f get() = Vec4f(x, y, y, y)
inline val Vec3f.xyyx: Vec4f get() = Vec4f(x, y, y, x)
inline val Vec3f.xyxz: Vec4f get() = Vec4f(x, y, x, z)
inline val Vec3f.xyxy: Vec4f get() = Vec4f(x, y, x, y)
inline val Vec3f.xyxx: Vec4f get() = Vec4f(x, y, x, x)
inline val Vec3f.xxzz: Vec4f get() = Vec4f(x, x, z, z)
inline val Vec3f.xxzy: Vec4f get() = Vec4f(x, x, z, y)
inline val Vec3f.xxzx: Vec4f get() = Vec4f(x, x, z, x)
inline val Vec3f.xxyz: Vec4f get() = Vec4f(x, x, y, z)
inline val Vec3f.xxyy: Vec4f get() = Vec4f(x, x, y, y)
inline val Vec3f.xxyx: Vec4f get() = Vec4f(x, x, y, x)
inline val Vec3f.xxxz: Vec4f get() = Vec4f(x, x, x, z)
inline val Vec3f.xxxy: Vec4f get() = Vec4f(x, x, x, y)
inline val Vec3f.xxxx: Vec4f get() = Vec4f(x, x, x, x)

// Vec4f non-duplicate l-value swizzling xyzw
inline var Vec4f.xy:   Vec2f get() = Vec2f(x, y);       set(value) { x = value.x; y = value.y }
inline var Vec4f.xz:   Vec2f get() = Vec2f(x, z);       set(value) { x = value.x; z = value.y }
inline var Vec4f.xw:   Vec2f get() = Vec2f(x, w);       set(value) { x = value.x; w = value.y }
inline var Vec4f.yx:   Vec2f get() = Vec2f(y, x);       set(value) { y = value.x; x = value.y }
inline var Vec4f.yz:   Vec2f get() = Vec2f(y, z);       set(value) { y = value.x; z = value.y }
inline var Vec4f.yw:   Vec2f get() = Vec2f(y, w);       set(value) { y = value.x; w = value.y }
inline var Vec4f.zx:   Vec2f get() = Vec2f(z, x);       set(value) { z = value.x; x = value.y }
inline var Vec4f.zy:   Vec2f get() = Vec2f(z, y);       set(value) { z = value.x; y = value.y }
inline var Vec4f.zw:   Vec2f get() = Vec2f(z, w);       set(value) { z = value.x; w = value.y }
inline var Vec4f.wx:   Vec2f get() = Vec2f(w, x);       set(value) { w = value.x; x = value.y }
inline var Vec4f.wy:   Vec2f get() = Vec2f(w, y);       set(value) { w = value.x; y = value.y }
inline var Vec4f.wz:   Vec2f get() = Vec2f(w, z);       set(value) { w = value.x; z = value.y }
inline var Vec4f.xyz:  Vec3f get() = Vec3f(x, y, z);    set(value) { x = value.x; y = value.y; z = value.z }
inline var Vec4f.xyw:  Vec3f get() = Vec3f(x, y, w);    set(value) { x = value.x; y = value.y; w = value.z }
inline var Vec4f.xzy:  Vec3f get() = Vec3f(x, z, y);    set(value) { x = value.x; z = value.y; y = value.z }
inline var Vec4f.xzw:  Vec3f get() = Vec3f(x, z, w);    set(value) { x = value.x; z = value.y; w = value.z }
inline var Vec4f.xwy:  Vec3f get() = Vec3f(x, w, y);    set(value) { x = value.x; w = value.y; y = value.z }
inline var Vec4f.xwz:  Vec3f get() = Vec3f(x, w, z);    set(value) { x = value.x; w = value.y; z = value.z }
inline var Vec4f.yxz:  Vec3f get() = Vec3f(y, x, z);    set(value) { y = value.x; x = value.y; z = value.z }
inline var Vec4f.yxw:  Vec3f get() = Vec3f(y, x, w);    set(value) { y = value.x; x = value.y; w = value.z }
inline var Vec4f.yzx:  Vec3f get() = Vec3f(y, z, x);    set(value) { y = value.x; z = value.y; x = value.z }
inline var Vec4f.yzw:  Vec3f get() = Vec3f(y, z, w);    set(value) { y = value.x; z = value.y; w = value.z }
inline var Vec4f.ywx:  Vec3f get() = Vec3f(y, w, x);    set(value) { y = value.x; w = value.y; x = value.z }
inline var Vec4f.ywz:  Vec3f get() = Vec3f(y, w, z);    set(value) { y = value.x; w = value.y; z = value.z }
inline var Vec4f.zxy:  Vec3f get() = Vec3f(z, x, y);    set(value) { z = value.x; x = value.y; y = value.z }
inline var Vec4f.zxw:  Vec3f get() = Vec3f(z, x, w);    set(value) { z = value.x; x = value.y; w = value.z }
inline var Vec4f.zyx:  Vec3f get() = Vec3f(z, y, x);    set(value) { z = value.x; y = value.y; x = value.z }
inline var Vec4f.zyw:  Vec3f get() = Vec3f(z, y, w);    set(value) { z = value.x; y = value.y; w = value.z }
inline var Vec4f.zwx:  Vec3f get() = Vec3f(z, w, x);    set(value) { z = value.x; w = value.y; x = value.z }
inline var Vec4f.zwy:  Vec3f get() = Vec3f(z, w, y);    set(value) { z = value.x; w = value.y; y = value.z }
inline var Vec4f.wxy:  Vec3f get() = Vec3f(w, x, y);    set(value) { w = value.x; x = value.y; y = value.z }
inline var Vec4f.wxz:  Vec3f get() = Vec3f(w, x, z);    set(value) { w = value.x; x = value.y; z = value.z }
inline var Vec4f.wyx:  Vec3f get() = Vec3f(w, y, x);    set(value) { w = value.x; y = value.y; x = value.z }
inline var Vec4f.wyz:  Vec3f get() = Vec3f(w, y, z);    set(value) { w = value.x; y = value.y; z = value.z }
inline var Vec4f.wzx:  Vec3f get() = Vec3f(w, z, x);    set(value) { w = value.x; z = value.y; x = value.z }
inline var Vec4f.wzy:  Vec3f get() = Vec3f(w, z, y);    set(value) { w = value.x; z = value.y; y = value.z }
inline var Vec4f.xyzw: Vec4f get() = Vec4f(x, y, z, w); set(value) { x = value.x; y = value.y; z = value.z; w = value.w }
inline var Vec4f.xywz: Vec4f get() = Vec4f(x, y, w, z); set(value) { x = value.x; y = value.y; w = value.z; z = value.w }
inline var Vec4f.xzyw: Vec4f get() = Vec4f(x, z, y, w); set(value) { x = value.x; z = value.y; y = value.z; w = value.w }
inline var Vec4f.xzwy: Vec4f get() = Vec4f(x, z, w, y); set(value) { x = value.x; z = value.y; w = value.z; y = value.w }
inline var Vec4f.xwyz: Vec4f get() = Vec4f(x, w, y, z); set(value) { x = value.x; w = value.y; y = value.z; z = value.w }
inline var Vec4f.xwzy: Vec4f get() = Vec4f(x, w, z, y); set(value) { x = value.x; w = value.y; z = value.z; y = value.w }
inline var Vec4f.yxzw: Vec4f get() = Vec4f(y, x, z, w); set(value) { y = value.x; x = value.y; z = value.z; w = value.w }
inline var Vec4f.yxwz: Vec4f get() = Vec4f(y, x, w, z); set(value) { y = value.x; x = value.y; w = value.z; z = value.w }
inline var Vec4f.yzxw: Vec4f get() = Vec4f(y, z, x, w); set(value) { y = value.x; z = value.y; x = value.z; w = value.w }
inline var Vec4f.yzwx: Vec4f get() = Vec4f(y, z, w, x); set(value) { y = value.x; z = value.y; w = value.z; x = value.w }
inline var Vec4f.ywxz: Vec4f get() = Vec4f(y, w, x, z); set(value) { y = value.x; w = value.y; x = value.z; z = value.w }
inline var Vec4f.ywzx: Vec4f get() = Vec4f(y, w, z, x); set(value) { y = value.x; w = value.y; z = value.z; x = value.w }
inline var Vec4f.zxyw: Vec4f get() = Vec4f(z, x, y, w); set(value) { z = value.x; x = value.y; y = value.z; w = value.w }
inline var Vec4f.zxwy: Vec4f get() = Vec4f(z, x, w, y); set(value) { z = value.x; x = value.y; w = value.z; y = value.w }
inline var Vec4f.zyxw: Vec4f get() = Vec4f(z, y, x, w); set(value) { z = value.x; y = value.y; x = value.z; w = value.w }
inline var Vec4f.zywx: Vec4f get() = Vec4f(z, y, w, x); set(value) { z = value.x; y = value.y; w = value.z; x = value.w }
inline var Vec4f.zwxy: Vec4f get() = Vec4f(z, w, x, y); set(value) { z = value.x; w = value.y; x = value.z; y = value.w }
inline var Vec4f.zwyx: Vec4f get() = Vec4f(z, w, y, x); set(value) { z = value.x; w = value.y; y = value.z; x = value.w }
inline var Vec4f.wxyz: Vec4f get() = Vec4f(w, x, y, z); set(value) { w = value.x; x = value.y; y = value.z; z = value.w }
inline var Vec4f.wxzy: Vec4f get() = Vec4f(w, x, z, y); set(value) { w = value.x; x = value.y; z = value.z; y = value.w }
inline var Vec4f.wyxz: Vec4f get() = Vec4f(w, y, x, z); set(value) { w = value.x; y = value.y; x = value.z; z = value.w }
inline var Vec4f.wyzx: Vec4f get() = Vec4f(w, y, z, x); set(value) { w = value.x; y = value.y; z = value.z; x = value.w }
inline var Vec4f.wzxy: Vec4f get() = Vec4f(w, z, x, y); set(value) { w = value.x; z = value.y; x = value.z; y = value.w }
inline var Vec4f.wzyx: Vec4f get() = Vec4f(w, z, y, x); set(value) { w = value.x; z = value.y; y = value.z; x = value.w }

// Vec4f duplicate l-value swizzling xyzw
inline val Vec4f.xx: Vec2f get() = Vec2f(x, x)
inline val Vec4f.yy: Vec2f get() = Vec2f(x, x)
inline val Vec4f.zz: Vec2f get() = Vec2f(x, x)
inline val Vec4f.ww: Vec2f get() = Vec2f(x, x)
inline val Vec4f.xxx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xxy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xxz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xxw: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xyx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xyy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xzx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xzz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xwx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xww: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yxx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yxy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yyx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yyy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yyz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yyw: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yzy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yzz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.ywy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.yww: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zxx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zxz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zyy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zyz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zzx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zzy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zzz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zzw: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zwz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.zww: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wxx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wxw: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wyy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wyw: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wzz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wzw: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wwx: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wwy: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.wwz: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.www: Vec3f get() = Vec3f(x, x, x)
inline val Vec4f.xxxx: Vec4f get() = Vec4f(x, x, x, x)
inline val Vec4f.xxxy: Vec4f get() = Vec4f(x, x, x, y)
inline val Vec4f.xxxz: Vec4f get() = Vec4f(x, x, x, z)
inline val Vec4f.xxxw: Vec4f get() = Vec4f(x, x, x, w)
inline val Vec4f.xxyx: Vec4f get() = Vec4f(x, x, y, x)
inline val Vec4f.xxyy: Vec4f get() = Vec4f(x, x, y, y)
inline val Vec4f.xxyz: Vec4f get() = Vec4f(x, x, y, z)
inline val Vec4f.xxyw: Vec4f get() = Vec4f(x, x, y, w)
inline val Vec4f.xxzx: Vec4f get() = Vec4f(x, x, z, x)
inline val Vec4f.xxzy: Vec4f get() = Vec4f(x, x, z, y)
inline val Vec4f.xxzz: Vec4f get() = Vec4f(x, x, z, z)
inline val Vec4f.xxzw: Vec4f get() = Vec4f(x, x, z, w)
inline val Vec4f.xxwx: Vec4f get() = Vec4f(x, x, w, x)
inline val Vec4f.xxwy: Vec4f get() = Vec4f(x, x, w, y)
inline val Vec4f.xxwz: Vec4f get() = Vec4f(x, x, w, z)
inline val Vec4f.xxww: Vec4f get() = Vec4f(x, x, w, w)
inline val Vec4f.xyxx: Vec4f get() = Vec4f(x, y, x, x)
inline val Vec4f.xyxy: Vec4f get() = Vec4f(x, y, x, y)
inline val Vec4f.xyxz: Vec4f get() = Vec4f(x, y, x, z)
inline val Vec4f.xyxw: Vec4f get() = Vec4f(x, y, x, w)
inline val Vec4f.xyyx: Vec4f get() = Vec4f(x, y, y, x)
inline val Vec4f.xyyy: Vec4f get() = Vec4f(x, y, y, y)
inline val Vec4f.xyyz: Vec4f get() = Vec4f(x, y, y, z)
inline val Vec4f.xyyw: Vec4f get() = Vec4f(x, y, y, w)
inline val Vec4f.xyzx: Vec4f get() = Vec4f(x, y, z, x)
inline val Vec4f.xyzy: Vec4f get() = Vec4f(x, y, z, y)
inline val Vec4f.xyzz: Vec4f get() = Vec4f(x, y, z, z)
inline val Vec4f.xywx: Vec4f get() = Vec4f(x, y, w, x)
inline val Vec4f.xywy: Vec4f get() = Vec4f(x, y, w, y)
inline val Vec4f.xyww: Vec4f get() = Vec4f(x, y, w, w)
inline val Vec4f.xzxx: Vec4f get() = Vec4f(x, z, x, x)
inline val Vec4f.xzxy: Vec4f get() = Vec4f(x, z, x, y)
inline val Vec4f.xzxz: Vec4f get() = Vec4f(x, z, x, z)
inline val Vec4f.xzxw: Vec4f get() = Vec4f(x, z, x, w)
inline val Vec4f.xzyx: Vec4f get() = Vec4f(x, z, y, x)
inline val Vec4f.xzyy: Vec4f get() = Vec4f(x, z, y, y)
inline val Vec4f.xzyz: Vec4f get() = Vec4f(x, z, y, z)
inline val Vec4f.xzzx: Vec4f get() = Vec4f(x, z, z, x)
inline val Vec4f.xzzy: Vec4f get() = Vec4f(x, z, z, y)
inline val Vec4f.xzzz: Vec4f get() = Vec4f(x, z, z, z)
inline val Vec4f.xzzw: Vec4f get() = Vec4f(x, z, z, w)
inline val Vec4f.xzwx: Vec4f get() = Vec4f(x, z, w, x)
inline val Vec4f.xzwz: Vec4f get() = Vec4f(x, z, w, z)
inline val Vec4f.xzww: Vec4f get() = Vec4f(x, z, w, w)
inline val Vec4f.xwxx: Vec4f get() = Vec4f(x, w, x, x)
inline val Vec4f.xwxy: Vec4f get() = Vec4f(x, w, x, y)
inline val Vec4f.xwxz: Vec4f get() = Vec4f(x, w, x, z)
inline val Vec4f.xwxw: Vec4f get() = Vec4f(x, w, x, w)
inline val Vec4f.xwyx: Vec4f get() = Vec4f(x, w, y, x)
inline val Vec4f.xwyy: Vec4f get() = Vec4f(x, w, y, y)
inline val Vec4f.xwyw: Vec4f get() = Vec4f(x, w, y, w)
inline val Vec4f.xwzx: Vec4f get() = Vec4f(x, w, z, x)
inline val Vec4f.xwzz: Vec4f get() = Vec4f(x, w, z, z)
inline val Vec4f.xwzw: Vec4f get() = Vec4f(x, w, z, w)
inline val Vec4f.xwwx: Vec4f get() = Vec4f(x, w, w, x)
inline val Vec4f.xwwy: Vec4f get() = Vec4f(x, w, w, y)
inline val Vec4f.xwwz: Vec4f get() = Vec4f(x, w, w, z)
inline val Vec4f.xwww: Vec4f get() = Vec4f(x, w, w, w)
inline val Vec4f.yxxx: Vec4f get() = Vec4f(y, x, x, x)
inline val Vec4f.yxxy: Vec4f get() = Vec4f(y, x, x, y)
inline val Vec4f.yxxz: Vec4f get() = Vec4f(y, x, x, z)
inline val Vec4f.yxxw: Vec4f get() = Vec4f(y, x, x, w)
inline val Vec4f.yxyx: Vec4f get() = Vec4f(y, x, y, x)
inline val Vec4f.yxyy: Vec4f get() = Vec4f(y, x, y, y)
inline val Vec4f.yxyz: Vec4f get() = Vec4f(y, x, y, z)
inline val Vec4f.yxyw: Vec4f get() = Vec4f(y, x, y, w)
inline val Vec4f.yxzx: Vec4f get() = Vec4f(y, x, z, x)
inline val Vec4f.yxzy: Vec4f get() = Vec4f(y, x, z, y)
inline val Vec4f.yxzz: Vec4f get() = Vec4f(y, x, z, z)
inline val Vec4f.yxwx: Vec4f get() = Vec4f(y, x, w, x)
inline val Vec4f.yxwy: Vec4f get() = Vec4f(y, x, w, y)
inline val Vec4f.yxww: Vec4f get() = Vec4f(y, x, w, w)
inline val Vec4f.yyxx: Vec4f get() = Vec4f(y, y, x, x)
inline val Vec4f.yyxy: Vec4f get() = Vec4f(y, y, x, y)
inline val Vec4f.yyxz: Vec4f get() = Vec4f(y, y, x, z)
inline val Vec4f.yyxw: Vec4f get() = Vec4f(y, y, x, w)
inline val Vec4f.yyyx: Vec4f get() = Vec4f(y, y, y, x)
inline val Vec4f.yyyy: Vec4f get() = Vec4f(y, y, y, y)
inline val Vec4f.yyyz: Vec4f get() = Vec4f(y, y, y, z)
inline val Vec4f.yyyw: Vec4f get() = Vec4f(y, y, y, w)
inline val Vec4f.yyzx: Vec4f get() = Vec4f(y, y, z, x)
inline val Vec4f.yyzy: Vec4f get() = Vec4f(y, y, z, y)
inline val Vec4f.yyzz: Vec4f get() = Vec4f(y, y, z, z)
inline val Vec4f.yyzw: Vec4f get() = Vec4f(y, y, z, w)
inline val Vec4f.yywx: Vec4f get() = Vec4f(y, y, w, x)
inline val Vec4f.yywy: Vec4f get() = Vec4f(y, y, w, y)
inline val Vec4f.yywz: Vec4f get() = Vec4f(y, y, w, z)
inline val Vec4f.yyww: Vec4f get() = Vec4f(y, y, w, w)
inline val Vec4f.yzxx: Vec4f get() = Vec4f(y, z, x, x)
inline val Vec4f.yzxy: Vec4f get() = Vec4f(y, z, x, y)
inline val Vec4f.yzxz: Vec4f get() = Vec4f(y, z, x, z)
inline val Vec4f.yzyx: Vec4f get() = Vec4f(y, z, y, x)
inline val Vec4f.yzyy: Vec4f get() = Vec4f(y, z, y, y)
inline val Vec4f.yzyz: Vec4f get() = Vec4f(y, z, y, z)
inline val Vec4f.yzyw: Vec4f get() = Vec4f(y, z, y, w)
inline val Vec4f.yzzx: Vec4f get() = Vec4f(y, z, z, x)
inline val Vec4f.yzzy: Vec4f get() = Vec4f(y, z, z, y)
inline val Vec4f.yzzz: Vec4f get() = Vec4f(y, z, z, z)
inline val Vec4f.yzzw: Vec4f get() = Vec4f(y, z, z, w)
inline val Vec4f.yzwy: Vec4f get() = Vec4f(y, z, w, y)
inline val Vec4f.yzwz: Vec4f get() = Vec4f(y, z, w, z)
inline val Vec4f.yzww: Vec4f get() = Vec4f(y, z, w, w)
inline val Vec4f.ywxx: Vec4f get() = Vec4f(y, w, x, x)
inline val Vec4f.ywxy: Vec4f get() = Vec4f(y, w, x, y)
inline val Vec4f.ywxw: Vec4f get() = Vec4f(y, w, x, w)
inline val Vec4f.ywyx: Vec4f get() = Vec4f(y, w, y, x)
inline val Vec4f.ywyy: Vec4f get() = Vec4f(y, w, y, y)
inline val Vec4f.ywyz: Vec4f get() = Vec4f(y, w, y, z)
inline val Vec4f.ywyw: Vec4f get() = Vec4f(y, w, y, w)
inline val Vec4f.ywzy: Vec4f get() = Vec4f(y, w, z, y)
inline val Vec4f.ywzz: Vec4f get() = Vec4f(y, w, z, z)
inline val Vec4f.ywzw: Vec4f get() = Vec4f(y, w, z, w)
inline val Vec4f.ywwx: Vec4f get() = Vec4f(y, w, w, x)
inline val Vec4f.ywwy: Vec4f get() = Vec4f(y, w, w, y)
inline val Vec4f.ywwz: Vec4f get() = Vec4f(y, w, w, z)
inline val Vec4f.ywww: Vec4f get() = Vec4f(y, w, w, w)
inline val Vec4f.zxxx: Vec4f get() = Vec4f(z, x, x, x)
inline val Vec4f.zxxy: Vec4f get() = Vec4f(z, x, x, y)
inline val Vec4f.zxxz: Vec4f get() = Vec4f(z, x, x, z)
inline val Vec4f.zxxw: Vec4f get() = Vec4f(z, x, x, w)
inline val Vec4f.zxyx: Vec4f get() = Vec4f(z, x, y, x)
inline val Vec4f.zxyy: Vec4f get() = Vec4f(z, x, y, y)
inline val Vec4f.zxyz: Vec4f get() = Vec4f(z, x, y, z)
inline val Vec4f.zxzx: Vec4f get() = Vec4f(z, x, z, x)
inline val Vec4f.zxzy: Vec4f get() = Vec4f(z, x, z, y)
inline val Vec4f.zxzz: Vec4f get() = Vec4f(z, x, z, z)
inline val Vec4f.zxzw: Vec4f get() = Vec4f(z, x, z, w)
inline val Vec4f.zxwx: Vec4f get() = Vec4f(z, x, w, x)
inline val Vec4f.zxwz: Vec4f get() = Vec4f(z, x, w, z)
inline val Vec4f.zxww: Vec4f get() = Vec4f(z, x, w, w)
inline val Vec4f.zyxx: Vec4f get() = Vec4f(z, y, x, x)
inline val Vec4f.zyxy: Vec4f get() = Vec4f(z, y, x, y)
inline val Vec4f.zyxz: Vec4f get() = Vec4f(z, y, x, z)
inline val Vec4f.zyyx: Vec4f get() = Vec4f(z, y, y, x)
inline val Vec4f.zyyy: Vec4f get() = Vec4f(z, y, y, y)
inline val Vec4f.zyyz: Vec4f get() = Vec4f(z, y, y, z)
inline val Vec4f.zyyw: Vec4f get() = Vec4f(z, y, y, w)
inline val Vec4f.zyzx: Vec4f get() = Vec4f(z, y, z, x)
inline val Vec4f.zyzy: Vec4f get() = Vec4f(z, y, z, y)
inline val Vec4f.zyzz: Vec4f get() = Vec4f(z, y, z, z)
inline val Vec4f.zyzw: Vec4f get() = Vec4f(z, y, z, w)
inline val Vec4f.zywy: Vec4f get() = Vec4f(z, y, w, y)
inline val Vec4f.zywz: Vec4f get() = Vec4f(z, y, w, z)
inline val Vec4f.zyww: Vec4f get() = Vec4f(z, y, w, w)
inline val Vec4f.zzxx: Vec4f get() = Vec4f(z, z, x, x)
inline val Vec4f.zzxy: Vec4f get() = Vec4f(z, z, x, y)
inline val Vec4f.zzxz: Vec4f get() = Vec4f(z, z, x, z)
inline val Vec4f.zzxw: Vec4f get() = Vec4f(z, z, x, w)
inline val Vec4f.zzyx: Vec4f get() = Vec4f(z, z, y, x)
inline val Vec4f.zzyy: Vec4f get() = Vec4f(z, z, y, y)
inline val Vec4f.zzyz: Vec4f get() = Vec4f(z, z, y, z)
inline val Vec4f.zzyw: Vec4f get() = Vec4f(z, z, y, w)
inline val Vec4f.zzzx: Vec4f get() = Vec4f(z, z, z, x)
inline val Vec4f.zzzy: Vec4f get() = Vec4f(z, z, z, y)
inline val Vec4f.zzzz: Vec4f get() = Vec4f(z, z, z, z)
inline val Vec4f.zzzw: Vec4f get() = Vec4f(z, z, z, w)
inline val Vec4f.zzwx: Vec4f get() = Vec4f(z, z, w, x)
inline val Vec4f.zzwy: Vec4f get() = Vec4f(z, z, w, y)
inline val Vec4f.zzwz: Vec4f get() = Vec4f(z, z, w, z)
inline val Vec4f.zzww: Vec4f get() = Vec4f(z, z, w, w)
inline val Vec4f.zwxx: Vec4f get() = Vec4f(z, w, x, x)
inline val Vec4f.zwxz: Vec4f get() = Vec4f(z, w, x, z)
inline val Vec4f.zwxw: Vec4f get() = Vec4f(z, w, x, w)
inline val Vec4f.zwyy: Vec4f get() = Vec4f(z, w, y, y)
inline val Vec4f.zwyz: Vec4f get() = Vec4f(z, w, y, z)
inline val Vec4f.zwyw: Vec4f get() = Vec4f(z, w, y, w)
inline val Vec4f.zwzx: Vec4f get() = Vec4f(z, w, z, x)
inline val Vec4f.zwzy: Vec4f get() = Vec4f(z, w, z, y)
inline val Vec4f.zwzz: Vec4f get() = Vec4f(z, w, z, z)
inline val Vec4f.zwzw: Vec4f get() = Vec4f(z, w, z, w)
inline val Vec4f.zwwx: Vec4f get() = Vec4f(z, w, w, x)
inline val Vec4f.zwwy: Vec4f get() = Vec4f(z, w, w, y)
inline val Vec4f.zwwz: Vec4f get() = Vec4f(z, w, w, z)
inline val Vec4f.zwww: Vec4f get() = Vec4f(z, w, w, w)
inline val Vec4f.wxxx: Vec4f get() = Vec4f(w, x, x, x)
inline val Vec4f.wxxy: Vec4f get() = Vec4f(w, x, x, y)
inline val Vec4f.wxxz: Vec4f get() = Vec4f(w, x, x, z)
inline val Vec4f.wxxw: Vec4f get() = Vec4f(w, x, x, w)
inline val Vec4f.wxyx: Vec4f get() = Vec4f(w, x, y, x)
inline val Vec4f.wxyy: Vec4f get() = Vec4f(w, x, y, y)
inline val Vec4f.wxyw: Vec4f get() = Vec4f(w, x, y, w)
inline val Vec4f.wxzx: Vec4f get() = Vec4f(w, x, z, x)
inline val Vec4f.wxzz: Vec4f get() = Vec4f(w, x, z, z)
inline val Vec4f.wxzw: Vec4f get() = Vec4f(w, x, z, w)
inline val Vec4f.wxwx: Vec4f get() = Vec4f(w, x, w, x)
inline val Vec4f.wxwy: Vec4f get() = Vec4f(w, x, w, y)
inline val Vec4f.wxwz: Vec4f get() = Vec4f(w, x, w, z)
inline val Vec4f.wxww: Vec4f get() = Vec4f(w, x, w, w)
inline val Vec4f.wyxx: Vec4f get() = Vec4f(w, y, x, x)
inline val Vec4f.wyxy: Vec4f get() = Vec4f(w, y, x, y)
inline val Vec4f.wyxw: Vec4f get() = Vec4f(w, y, x, w)
inline val Vec4f.wyyx: Vec4f get() = Vec4f(w, y, y, x)
inline val Vec4f.wyyy: Vec4f get() = Vec4f(w, y, y, y)
inline val Vec4f.wyyz: Vec4f get() = Vec4f(w, y, y, z)
inline val Vec4f.wyyw: Vec4f get() = Vec4f(w, y, y, w)
inline val Vec4f.wyzy: Vec4f get() = Vec4f(w, y, z, y)
inline val Vec4f.wyzz: Vec4f get() = Vec4f(w, y, z, z)
inline val Vec4f.wyzw: Vec4f get() = Vec4f(w, y, z, w)
inline val Vec4f.wywx: Vec4f get() = Vec4f(w, y, w, x)
inline val Vec4f.wywy: Vec4f get() = Vec4f(w, y, w, y)
inline val Vec4f.wywz: Vec4f get() = Vec4f(w, y, w, z)
inline val Vec4f.wyww: Vec4f get() = Vec4f(w, y, w, w)
inline val Vec4f.wzxx: Vec4f get() = Vec4f(w, z, x, x)
inline val Vec4f.wzxz: Vec4f get() = Vec4f(w, z, x, z)
inline val Vec4f.wzxw: Vec4f get() = Vec4f(w, z, x, w)
inline val Vec4f.wzyy: Vec4f get() = Vec4f(w, z, y, y)
inline val Vec4f.wzyz: Vec4f get() = Vec4f(w, z, y, z)
inline val Vec4f.wzyw: Vec4f get() = Vec4f(w, z, y, w)
inline val Vec4f.wzzx: Vec4f get() = Vec4f(w, z, z, x)
inline val Vec4f.wzzy: Vec4f get() = Vec4f(w, z, z, y)
inline val Vec4f.wzzz: Vec4f get() = Vec4f(w, z, z, z)
inline val Vec4f.wzzw: Vec4f get() = Vec4f(w, z, z, w)
inline val Vec4f.wzwx: Vec4f get() = Vec4f(w, z, w, x)
inline val Vec4f.wzwy: Vec4f get() = Vec4f(w, z, w, y)
inline val Vec4f.wzwz: Vec4f get() = Vec4f(w, z, w, z)
inline val Vec4f.wzww: Vec4f get() = Vec4f(w, z, w, w)
inline val Vec4f.wwxx: Vec4f get() = Vec4f(w, w, x, x)
inline val Vec4f.wwxy: Vec4f get() = Vec4f(w, w, x, y)
inline val Vec4f.wwxz: Vec4f get() = Vec4f(w, w, x, z)
inline val Vec4f.wwxw: Vec4f get() = Vec4f(w, w, x, w)
inline val Vec4f.wwyx: Vec4f get() = Vec4f(w, w, y, x)
inline val Vec4f.wwyy: Vec4f get() = Vec4f(w, w, y, y)
inline val Vec4f.wwyz: Vec4f get() = Vec4f(w, w, y, z)
inline val Vec4f.wwyw: Vec4f get() = Vec4f(w, w, y, w)
inline val Vec4f.wwzx: Vec4f get() = Vec4f(w, w, z, x)
inline val Vec4f.wwzy: Vec4f get() = Vec4f(w, w, z, y)
inline val Vec4f.wwzz: Vec4f get() = Vec4f(w, w, z, z)
inline val Vec4f.wwzw: Vec4f get() = Vec4f(w, w, z, w)
inline val Vec4f.wwwx: Vec4f get() = Vec4f(w, w, w, x)
inline val Vec4f.wwwy: Vec4f get() = Vec4f(w, w, w, y)
inline val Vec4f.wwwz: Vec4f get() = Vec4f(w, w, w, z)
inline val Vec4f.wwww: Vec4f get() = Vec4f(w, w, w, w)

// Vec2f non-duplicate l-value swizzling rg
inline var Vec2f.rg: Vec2f get() = Vec2f(r, g); set(value) { r = value.r; g = value.g }
inline var Vec2f.gr: Vec2f get() = Vec2f(g, r); set(value) { g = value.r; r = value.g }

// Vec2f duplicate l-value swizzling rg
inline val Vec2f.rr:   Vec2f get() = Vec2f(r, r)
inline val Vec2f.gg:   Vec2f get() = Vec2f(g, g)
inline val Vec2f.ggg:  Vec3f get() = Vec3f(g, g, g)
inline val Vec2f.ggr:  Vec3f get() = Vec3f(g, g, r)
inline val Vec2f.grg:  Vec3f get() = Vec3f(g, r, g)
inline val Vec2f.grr:  Vec3f get() = Vec3f(g, r, r)
inline val Vec2f.rgg:  Vec3f get() = Vec3f(r, g, g)
inline val Vec2f.rgr:  Vec3f get() = Vec3f(r, g, r)
inline val Vec2f.rrg:  Vec3f get() = Vec3f(r, r, g)
inline val Vec2f.rrr:  Vec3f get() = Vec3f(r, r, r)
inline val Vec2f.gggg: Vec4f get() = Vec4f(g, g, g, g)
inline val Vec2f.gggr: Vec4f get() = Vec4f(g, g, g, r)
inline val Vec2f.ggrg: Vec4f get() = Vec4f(g, g, r, g)
inline val Vec2f.ggrr: Vec4f get() = Vec4f(g, g, r, r)
inline val Vec2f.grgg: Vec4f get() = Vec4f(g, r, g, g)
inline val Vec2f.grgr: Vec4f get() = Vec4f(g, r, g, r)
inline val Vec2f.grrg: Vec4f get() = Vec4f(g, r, r, g)
inline val Vec2f.grrr: Vec4f get() = Vec4f(g, r, r, r)
inline val Vec2f.rggg: Vec4f get() = Vec4f(r, g, g, g)
inline val Vec2f.rggr: Vec4f get() = Vec4f(r, g, g, r)
inline val Vec2f.rgrg: Vec4f get() = Vec4f(r, g, r, g)
inline val Vec2f.rgrr: Vec4f get() = Vec4f(r, g, r, r)
inline val Vec2f.rrgg: Vec4f get() = Vec4f(r, r, g, g)
inline val Vec2f.rrgr: Vec4f get() = Vec4f(r, r, g, r)
inline val Vec2f.rrrg: Vec4f get() = Vec4f(r, r, r, g)
inline val Vec2f.rrrr: Vec4f get() = Vec4f(r, r, r, r)

// Vec3f non-duplicate l-value swizzling rgb
inline var Vec3f.rg:  Vec2f get() = Vec2f(r, g);    set(value) { r = value.r; g = value.g }
inline var Vec3f.gr:  Vec2f get() = Vec2f(g, r);    set(value) { g = value.r; r = value.g }
inline var Vec3f.bg:  Vec2f get() = Vec2f(b, g);    set(value) { b = value.r; g = value.g }
inline var Vec3f.gb:  Vec2f get() = Vec2f(g, b);    set(value) { g = value.r; b = value.g }
inline var Vec3f.rb:  Vec2f get() = Vec2f(r, b);    set(value) { r = value.r; b = value.g }
inline var Vec3f.br:  Vec2f get() = Vec2f(b, r);    set(value) { b = value.r; r = value.g }
inline var Vec3f.brg: Vec3f get() = Vec3f(b, r, g); set(value) { b = value.r; r = value.g; g = value.b }
inline var Vec3f.bgr: Vec3f get() = Vec3f(b, g, r); set(value) { b = value.r; g = value.g; r = value.b }
inline var Vec3f.rbg: Vec3f get() = Vec3f(r, b, g); set(value) { r = value.r; b = value.g; g = value.b }
inline var Vec3f.rgb: Vec3f get() = Vec3f(r, g, b); set(value) { r = value.r; g = value.g; b = value.b }
inline var Vec3f.grb: Vec3f get() = Vec3f(g, r, b); set(value) { g = value.r; r = value.g; b = value.b }
inline var Vec3f.gbr: Vec3f get() = Vec3f(g, b, r); set(value) { g = value.r; b = value.g; r = value.b }

// Vec3f duplicate l-value swizzling rgb
inline val Vec3f.rr:   Vec2f get() = Vec2f(r, r)
inline val Vec3f.gg:   Vec2f get() = Vec2f(g, g)
inline val Vec3f.bb:   Vec2f get() = Vec2f(b, b)
inline val Vec3f.bbb:  Vec3f get() = Vec3f(b, b, b)
inline val Vec3f.bbg:  Vec3f get() = Vec3f(b, b, g)
inline val Vec3f.bbr:  Vec3f get() = Vec3f(b, b, r)
inline val Vec3f.bgb:  Vec3f get() = Vec3f(b, g, b)
inline val Vec3f.bgg:  Vec3f get() = Vec3f(b, g, g)
inline val Vec3f.brb:  Vec3f get() = Vec3f(b, r, b)
inline val Vec3f.brr:  Vec3f get() = Vec3f(b, r, r)
inline val Vec3f.gbb:  Vec3f get() = Vec3f(g, b, b)
inline val Vec3f.gbg:  Vec3f get() = Vec3f(g, b, g)
inline val Vec3f.ggb:  Vec3f get() = Vec3f(g, g, b)
inline val Vec3f.ggg:  Vec3f get() = Vec3f(g, g, g)
inline val Vec3f.ggr:  Vec3f get() = Vec3f(g, g, r)
inline val Vec3f.grg:  Vec3f get() = Vec3f(g, r, g)
inline val Vec3f.grr:  Vec3f get() = Vec3f(g, r, r)
inline val Vec3f.rbb:  Vec3f get() = Vec3f(r, b, b)
inline val Vec3f.rbr:  Vec3f get() = Vec3f(r, b, r)
inline val Vec3f.rgg:  Vec3f get() = Vec3f(r, g, g)
inline val Vec3f.rgr:  Vec3f get() = Vec3f(r, g, r)
inline val Vec3f.rrb:  Vec3f get() = Vec3f(r, r, b)
inline val Vec3f.rrg:  Vec3f get() = Vec3f(r, r, g)
inline val Vec3f.rrr:  Vec3f get() = Vec3f(r, r, r)
inline val Vec3f.bbbb: Vec4f get() = Vec4f(b, b, b, b)
inline val Vec3f.bbbg: Vec4f get() = Vec4f(b, b, b, g)
inline val Vec3f.bbbr: Vec4f get() = Vec4f(b, b, b, r)
inline val Vec3f.bbgb: Vec4f get() = Vec4f(b, b, g, b)
inline val Vec3f.bbgg: Vec4f get() = Vec4f(b, b, g, g)
inline val Vec3f.bbgr: Vec4f get() = Vec4f(b, b, g, r)
inline val Vec3f.bbrb: Vec4f get() = Vec4f(b, b, r, b)
inline val Vec3f.bbrg: Vec4f get() = Vec4f(b, b, r, g)
inline val Vec3f.bbrr: Vec4f get() = Vec4f(b, b, r, r)
inline val Vec3f.bgbb: Vec4f get() = Vec4f(b, g, b, b)
inline val Vec3f.bgbg: Vec4f get() = Vec4f(b, g, b, g)
inline val Vec3f.bgbr: Vec4f get() = Vec4f(b, g, b, r)
inline val Vec3f.bggb: Vec4f get() = Vec4f(b, g, g, b)
inline val Vec3f.bggg: Vec4f get() = Vec4f(b, g, g, g)
inline val Vec3f.bggr: Vec4f get() = Vec4f(b, g, g, r)
inline val Vec3f.bgrb: Vec4f get() = Vec4f(b, g, r, b)
inline val Vec3f.bgrg: Vec4f get() = Vec4f(b, g, r, g)
inline val Vec3f.bgrr: Vec4f get() = Vec4f(b, g, r, r)
inline val Vec3f.brbb: Vec4f get() = Vec4f(b, r, b, b)
inline val Vec3f.brbg: Vec4f get() = Vec4f(b, r, b, g)
inline val Vec3f.brbr: Vec4f get() = Vec4f(b, r, b, r)
inline val Vec3f.brgb: Vec4f get() = Vec4f(b, r, g, b)
inline val Vec3f.brgg: Vec4f get() = Vec4f(b, r, g, g)
inline val Vec3f.brgr: Vec4f get() = Vec4f(b, r, g, r)
inline val Vec3f.brrb: Vec4f get() = Vec4f(b, r, r, b)
inline val Vec3f.brrg: Vec4f get() = Vec4f(b, r, r, g)
inline val Vec3f.brrr: Vec4f get() = Vec4f(b, r, r, r)
inline val Vec3f.gbbb: Vec4f get() = Vec4f(g, b, b, b)
inline val Vec3f.gbbg: Vec4f get() = Vec4f(g, b, b, g)
inline val Vec3f.gbbr: Vec4f get() = Vec4f(g, b, b, r)
inline val Vec3f.gbgb: Vec4f get() = Vec4f(g, b, g, b)
inline val Vec3f.gbgg: Vec4f get() = Vec4f(g, b, g, g)
inline val Vec3f.gbgr: Vec4f get() = Vec4f(g, b, g, r)
inline val Vec3f.gbrb: Vec4f get() = Vec4f(g, b, r, b)
inline val Vec3f.gbrg: Vec4f get() = Vec4f(g, b, r, g)
inline val Vec3f.gbrr: Vec4f get() = Vec4f(g, b, r, r)
inline val Vec3f.ggbb: Vec4f get() = Vec4f(g, g, b, b)
inline val Vec3f.ggbg: Vec4f get() = Vec4f(g, g, b, g)
inline val Vec3f.ggbr: Vec4f get() = Vec4f(g, g, b, r)
inline val Vec3f.gggb: Vec4f get() = Vec4f(g, g, g, b)
inline val Vec3f.gggg: Vec4f get() = Vec4f(g, g, g, g)
inline val Vec3f.gggr: Vec4f get() = Vec4f(g, g, g, r)
inline val Vec3f.ggrb: Vec4f get() = Vec4f(g, g, r, b)
inline val Vec3f.ggrg: Vec4f get() = Vec4f(g, g, r, g)
inline val Vec3f.ggrr: Vec4f get() = Vec4f(g, g, r, r)
inline val Vec3f.grbb: Vec4f get() = Vec4f(g, r, b, b)
inline val Vec3f.grbg: Vec4f get() = Vec4f(g, r, b, g)
inline val Vec3f.grbr: Vec4f get() = Vec4f(g, r, b, r)
inline val Vec3f.grgb: Vec4f get() = Vec4f(g, r, g, b)
inline val Vec3f.grgg: Vec4f get() = Vec4f(g, r, g, g)
inline val Vec3f.grgr: Vec4f get() = Vec4f(g, r, g, r)
inline val Vec3f.grrb: Vec4f get() = Vec4f(g, r, r, b)
inline val Vec3f.grrg: Vec4f get() = Vec4f(g, r, r, g)
inline val Vec3f.grrr: Vec4f get() = Vec4f(g, r, r, r)
inline val Vec3f.rbbb: Vec4f get() = Vec4f(r, b, b, b)
inline val Vec3f.rbbg: Vec4f get() = Vec4f(r, b, b, g)
inline val Vec3f.rbbr: Vec4f get() = Vec4f(r, b, b, r)
inline val Vec3f.rbgb: Vec4f get() = Vec4f(r, b, g, b)
inline val Vec3f.rbgg: Vec4f get() = Vec4f(r, b, g, g)
inline val Vec3f.rbgr: Vec4f get() = Vec4f(r, b, g, r)
inline val Vec3f.rbrb: Vec4f get() = Vec4f(r, b, r, b)
inline val Vec3f.rbrg: Vec4f get() = Vec4f(r, b, r, g)
inline val Vec3f.rbrr: Vec4f get() = Vec4f(r, b, r, r)
inline val Vec3f.rgbb: Vec4f get() = Vec4f(r, g, b, b)
inline val Vec3f.rgbg: Vec4f get() = Vec4f(r, g, b, g)
inline val Vec3f.rgbr: Vec4f get() = Vec4f(r, g, b, r)
inline val Vec3f.rggb: Vec4f get() = Vec4f(r, g, g, b)
inline val Vec3f.rggg: Vec4f get() = Vec4f(r, g, g, g)
inline val Vec3f.rggr: Vec4f get() = Vec4f(r, g, g, r)
inline val Vec3f.rgrb: Vec4f get() = Vec4f(r, g, r, b)
inline val Vec3f.rgrg: Vec4f get() = Vec4f(r, g, r, g)
inline val Vec3f.rgrr: Vec4f get() = Vec4f(r, g, r, r)
inline val Vec3f.rrbb: Vec4f get() = Vec4f(r, r, b, b)
inline val Vec3f.rrbg: Vec4f get() = Vec4f(r, r, b, g)
inline val Vec3f.rrbr: Vec4f get() = Vec4f(r, r, b, r)
inline val Vec3f.rrgb: Vec4f get() = Vec4f(r, r, g, b)
inline val Vec3f.rrgg: Vec4f get() = Vec4f(r, r, g, g)
inline val Vec3f.rrgr: Vec4f get() = Vec4f(r, r, g, r)
inline val Vec3f.rrrb: Vec4f get() = Vec4f(r, r, r, b)
inline val Vec3f.rrrg: Vec4f get() = Vec4f(r, r, r, g)
inline val Vec3f.rrrr: Vec4f get() = Vec4f(r, r, r, r)

// Vec4f non-duplicate l-value swizzling rgba
inline var Vec4f.rg:   Vec2f get() = Vec2f(r, g);       set(value) { r = value.r; g = value.g }
inline var Vec4f.rb:   Vec2f get() = Vec2f(r, b);       set(value) { r = value.r; b = value.g }
inline var Vec4f.ra:   Vec2f get() = Vec2f(r, a);       set(value) { r = value.r; a = value.g }
inline var Vec4f.gr:   Vec2f get() = Vec2f(g, r);       set(value) { g = value.r; r = value.g }
inline var Vec4f.gb:   Vec2f get() = Vec2f(g, b);       set(value) { g = value.r; b = value.g }
inline var Vec4f.ga:   Vec2f get() = Vec2f(g, a);       set(value) { g = value.r; a = value.g }
inline var Vec4f.br:   Vec2f get() = Vec2f(b, r);       set(value) { b = value.r; r = value.g }
inline var Vec4f.bg:   Vec2f get() = Vec2f(b, g);       set(value) { b = value.r; g = value.g }
inline var Vec4f.ba:   Vec2f get() = Vec2f(b, a);       set(value) { b = value.r; a = value.g }
inline var Vec4f.ar:   Vec2f get() = Vec2f(a, r);       set(value) { a = value.r; r = value.g }
inline var Vec4f.ag:   Vec2f get() = Vec2f(a, g);       set(value) { a = value.r; g = value.g }
inline var Vec4f.ab:   Vec2f get() = Vec2f(a, b);       set(value) { a = value.r; b = value.g }
inline var Vec4f.rgb:  Vec3f get() = Vec3f(r, g, b);    set(value) { r = value.r; g = value.g; b = value.b }
inline var Vec4f.rga:  Vec3f get() = Vec3f(r, g, a);    set(value) { r = value.r; g = value.g; a = value.b }
inline var Vec4f.rbg:  Vec3f get() = Vec3f(r, b, g);    set(value) { r = value.r; b = value.g; g = value.b }
inline var Vec4f.rba:  Vec3f get() = Vec3f(r, b, a);    set(value) { r = value.r; b = value.g; a = value.b }
inline var Vec4f.rag:  Vec3f get() = Vec3f(r, a, g);    set(value) { r = value.r; a = value.g; g = value.b }
inline var Vec4f.rab:  Vec3f get() = Vec3f(r, a, b);    set(value) { r = value.r; a = value.g; b = value.b }
inline var Vec4f.grb:  Vec3f get() = Vec3f(g, r, b);    set(value) { g = value.r; r = value.g; b = value.b }
inline var Vec4f.gra:  Vec3f get() = Vec3f(g, r, a);    set(value) { g = value.r; r = value.g; a = value.b }
inline var Vec4f.gbr:  Vec3f get() = Vec3f(g, b, r);    set(value) { g = value.r; b = value.g; r = value.b }
inline var Vec4f.gba:  Vec3f get() = Vec3f(g, b, a);    set(value) { g = value.r; b = value.g; a = value.b }
inline var Vec4f.gar:  Vec3f get() = Vec3f(g, a, r);    set(value) { g = value.r; a = value.g; r = value.b }
inline var Vec4f.gab:  Vec3f get() = Vec3f(g, a, b);    set(value) { g = value.r; a = value.g; b = value.b }
inline var Vec4f.brg:  Vec3f get() = Vec3f(b, r, g);    set(value) { b = value.r; r = value.g; g = value.b }
inline var Vec4f.bra:  Vec3f get() = Vec3f(b, r, a);    set(value) { b = value.r; r = value.g; a = value.b }
inline var Vec4f.bgr:  Vec3f get() = Vec3f(b, g, r);    set(value) { b = value.r; g = value.g; r = value.b }
inline var Vec4f.bga:  Vec3f get() = Vec3f(b, g, a);    set(value) { b = value.r; g = value.g; a = value.b }
inline var Vec4f.bar:  Vec3f get() = Vec3f(b, a, r);    set(value) { b = value.r; a = value.g; r = value.b }
inline var Vec4f.bag:  Vec3f get() = Vec3f(b, a, g);    set(value) { b = value.r; a = value.g; g = value.b }
inline var Vec4f.arg:  Vec3f get() = Vec3f(a, r, g);    set(value) { a = value.r; r = value.g; g = value.b }
inline var Vec4f.arb:  Vec3f get() = Vec3f(a, r, b);    set(value) { a = value.r; r = value.g; b = value.b }
inline var Vec4f.agr:  Vec3f get() = Vec3f(a, g, r);    set(value) { a = value.r; g = value.g; r = value.b }
inline var Vec4f.agb:  Vec3f get() = Vec3f(a, g, b);    set(value) { a = value.r; g = value.g; b = value.b }
inline var Vec4f.abr:  Vec3f get() = Vec3f(a, b, r);    set(value) { a = value.r; b = value.g; r = value.b }
inline var Vec4f.abg:  Vec3f get() = Vec3f(a, b, g);    set(value) { a = value.r; b = value.g; g = value.b }
inline var Vec4f.rgba: Vec4f get() = Vec4f(r, g, b, a); set(value) { r = value.r; g = value.g; b = value.b; a = value.a }
inline var Vec4f.rgab: Vec4f get() = Vec4f(r, g, a, b); set(value) { r = value.r; g = value.g; a = value.b; b = value.a }
inline var Vec4f.rbga: Vec4f get() = Vec4f(r, b, g, a); set(value) { r = value.r; b = value.g; g = value.b; a = value.a }
inline var Vec4f.rbag: Vec4f get() = Vec4f(r, b, a, g); set(value) { r = value.r; b = value.g; a = value.b; g = value.a }
inline var Vec4f.ragb: Vec4f get() = Vec4f(r, a, g, b); set(value) { r = value.r; a = value.g; g = value.b; b = value.a }
inline var Vec4f.rabg: Vec4f get() = Vec4f(r, a, b, g); set(value) { r = value.r; a = value.g; b = value.b; g = value.a }
inline var Vec4f.grba: Vec4f get() = Vec4f(g, r, b, a); set(value) { g = value.r; r = value.g; b = value.b; a = value.a }
inline var Vec4f.grab: Vec4f get() = Vec4f(g, r, a, b); set(value) { g = value.r; r = value.g; a = value.b; b = value.a }
inline var Vec4f.gbra: Vec4f get() = Vec4f(g, b, r, a); set(value) { g = value.r; b = value.g; r = value.b; a = value.a }
inline var Vec4f.gbar: Vec4f get() = Vec4f(g, b, a, r); set(value) { g = value.r; b = value.g; a = value.b; r = value.a }
inline var Vec4f.garb: Vec4f get() = Vec4f(g, a, r, b); set(value) { g = value.r; a = value.g; r = value.b; b = value.a }
inline var Vec4f.gabr: Vec4f get() = Vec4f(g, a, b, r); set(value) { g = value.r; a = value.g; b = value.b; r = value.a }
inline var Vec4f.brga: Vec4f get() = Vec4f(b, r, g, a); set(value) { b = value.r; r = value.g; g = value.b; a = value.a }
inline var Vec4f.brag: Vec4f get() = Vec4f(b, r, a, g); set(value) { b = value.r; r = value.g; a = value.b; g = value.a }
inline var Vec4f.bgra: Vec4f get() = Vec4f(b, g, r, a); set(value) { b = value.r; g = value.g; r = value.b; a = value.a }
inline var Vec4f.bgar: Vec4f get() = Vec4f(b, g, a, r); set(value) { b = value.r; g = value.g; a = value.b; r = value.a }
inline var Vec4f.barg: Vec4f get() = Vec4f(b, a, r, g); set(value) { b = value.r; a = value.g; r = value.b; g = value.a }
inline var Vec4f.bagr: Vec4f get() = Vec4f(b, a, g, r); set(value) { b = value.r; a = value.g; g = value.b; r = value.a }
inline var Vec4f.argb: Vec4f get() = Vec4f(a, r, g, b); set(value) { a = value.r; r = value.g; g = value.b; b = value.a }
inline var Vec4f.arbg: Vec4f get() = Vec4f(a, r, b, g); set(value) { a = value.r; r = value.g; b = value.b; g = value.a }
inline var Vec4f.agrb: Vec4f get() = Vec4f(a, g, r, b); set(value) { a = value.r; g = value.g; r = value.b; b = value.a }
inline var Vec4f.agbr: Vec4f get() = Vec4f(a, g, b, r); set(value) { a = value.r; g = value.g; b = value.b; r = value.a }
inline var Vec4f.abrg: Vec4f get() = Vec4f(a, b, r, g); set(value) { a = value.r; b = value.g; r = value.b; g = value.a }
inline var Vec4f.abgr: Vec4f get() = Vec4f(a, b, g, r); set(value) { a = value.r; b = value.g; g = value.b; r = value.a }

// Vec4f duplicate l-value swizzling rgba
inline val Vec4f.rr: Vec2f get() = Vec2f(r, r)
inline val Vec4f.gg: Vec2f get() = Vec2f(r, r)
inline val Vec4f.bb: Vec2f get() = Vec2f(r, r)
inline val Vec4f.aa: Vec2f get() = Vec2f(r, r)
inline val Vec4f.rrr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rrg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rrb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rra: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rgr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rgg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rbr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rbb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rar: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.raa: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.grr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.grg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.ggr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.ggg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.ggb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.gga: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.gbg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.gbb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.gag: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.gaa: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.brr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.brb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bgg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bgb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bbr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bbg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bbb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bba: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.bab: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.baa: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.arr: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.ara: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.agg: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.aga: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.abb: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.aba: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.aar: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.aag: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.aab: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.aaa: Vec3f get() = Vec3f(r, r, r)
inline val Vec4f.rrrr: Vec4f get() = Vec4f(r, r, r, r)
inline val Vec4f.rrrg: Vec4f get() = Vec4f(r, r, r, g)
inline val Vec4f.rrrb: Vec4f get() = Vec4f(r, r, r, b)
inline val Vec4f.rrra: Vec4f get() = Vec4f(r, r, r, a)
inline val Vec4f.rrgr: Vec4f get() = Vec4f(r, r, g, r)
inline val Vec4f.rrgg: Vec4f get() = Vec4f(r, r, g, g)
inline val Vec4f.rrgb: Vec4f get() = Vec4f(r, r, g, b)
inline val Vec4f.rrga: Vec4f get() = Vec4f(r, r, g, a)
inline val Vec4f.rrbr: Vec4f get() = Vec4f(r, r, b, r)
inline val Vec4f.rrbg: Vec4f get() = Vec4f(r, r, b, g)
inline val Vec4f.rrbb: Vec4f get() = Vec4f(r, r, b, b)
inline val Vec4f.rrba: Vec4f get() = Vec4f(r, r, b, a)
inline val Vec4f.rrar: Vec4f get() = Vec4f(r, r, a, r)
inline val Vec4f.rrag: Vec4f get() = Vec4f(r, r, a, g)
inline val Vec4f.rrab: Vec4f get() = Vec4f(r, r, a, b)
inline val Vec4f.rraa: Vec4f get() = Vec4f(r, r, a, a)
inline val Vec4f.rgrr: Vec4f get() = Vec4f(r, g, r, r)
inline val Vec4f.rgrg: Vec4f get() = Vec4f(r, g, r, g)
inline val Vec4f.rgrb: Vec4f get() = Vec4f(r, g, r, b)
inline val Vec4f.rgra: Vec4f get() = Vec4f(r, g, r, a)
inline val Vec4f.rggr: Vec4f get() = Vec4f(r, g, g, r)
inline val Vec4f.rggg: Vec4f get() = Vec4f(r, g, g, g)
inline val Vec4f.rggb: Vec4f get() = Vec4f(r, g, g, b)
inline val Vec4f.rgga: Vec4f get() = Vec4f(r, g, g, a)
inline val Vec4f.rgbr: Vec4f get() = Vec4f(r, g, b, r)
inline val Vec4f.rgbg: Vec4f get() = Vec4f(r, g, b, g)
inline val Vec4f.rgbb: Vec4f get() = Vec4f(r, g, b, b)
inline val Vec4f.rgar: Vec4f get() = Vec4f(r, g, a, r)
inline val Vec4f.rgag: Vec4f get() = Vec4f(r, g, a, g)
inline val Vec4f.rgaa: Vec4f get() = Vec4f(r, g, a, a)
inline val Vec4f.rbrr: Vec4f get() = Vec4f(r, b, r, r)
inline val Vec4f.rbrg: Vec4f get() = Vec4f(r, b, r, g)
inline val Vec4f.rbrb: Vec4f get() = Vec4f(r, b, r, b)
inline val Vec4f.rbra: Vec4f get() = Vec4f(r, b, r, a)
inline val Vec4f.rbgr: Vec4f get() = Vec4f(r, b, g, r)
inline val Vec4f.rbgg: Vec4f get() = Vec4f(r, b, g, g)
inline val Vec4f.rbgb: Vec4f get() = Vec4f(r, b, g, b)
inline val Vec4f.rbbr: Vec4f get() = Vec4f(r, b, b, r)
inline val Vec4f.rbbg: Vec4f get() = Vec4f(r, b, b, g)
inline val Vec4f.rbbb: Vec4f get() = Vec4f(r, b, b, b)
inline val Vec4f.rbba: Vec4f get() = Vec4f(r, b, b, a)
inline val Vec4f.rbar: Vec4f get() = Vec4f(r, b, a, r)
inline val Vec4f.rbab: Vec4f get() = Vec4f(r, b, a, b)
inline val Vec4f.rbaa: Vec4f get() = Vec4f(r, b, a, a)
inline val Vec4f.rarr: Vec4f get() = Vec4f(r, a, r, r)
inline val Vec4f.rarg: Vec4f get() = Vec4f(r, a, r, g)
inline val Vec4f.rarb: Vec4f get() = Vec4f(r, a, r, b)
inline val Vec4f.rara: Vec4f get() = Vec4f(r, a, r, a)
inline val Vec4f.ragr: Vec4f get() = Vec4f(r, a, g, r)
inline val Vec4f.ragg: Vec4f get() = Vec4f(r, a, g, g)
inline val Vec4f.raga: Vec4f get() = Vec4f(r, a, g, a)
inline val Vec4f.rabr: Vec4f get() = Vec4f(r, a, b, r)
inline val Vec4f.rabb: Vec4f get() = Vec4f(r, a, b, b)
inline val Vec4f.raba: Vec4f get() = Vec4f(r, a, b, a)
inline val Vec4f.raar: Vec4f get() = Vec4f(r, a, a, r)
inline val Vec4f.raag: Vec4f get() = Vec4f(r, a, a, g)
inline val Vec4f.raab: Vec4f get() = Vec4f(r, a, a, b)
inline val Vec4f.raaa: Vec4f get() = Vec4f(r, a, a, a)
inline val Vec4f.grrr: Vec4f get() = Vec4f(g, r, r, r)
inline val Vec4f.grrg: Vec4f get() = Vec4f(g, r, r, g)
inline val Vec4f.grrb: Vec4f get() = Vec4f(g, r, r, b)
inline val Vec4f.grra: Vec4f get() = Vec4f(g, r, r, a)
inline val Vec4f.grgr: Vec4f get() = Vec4f(g, r, g, r)
inline val Vec4f.grgg: Vec4f get() = Vec4f(g, r, g, g)
inline val Vec4f.grgb: Vec4f get() = Vec4f(g, r, g, b)
inline val Vec4f.grga: Vec4f get() = Vec4f(g, r, g, a)
inline val Vec4f.grbr: Vec4f get() = Vec4f(g, r, b, r)
inline val Vec4f.grbg: Vec4f get() = Vec4f(g, r, b, g)
inline val Vec4f.grbb: Vec4f get() = Vec4f(g, r, b, b)
inline val Vec4f.grar: Vec4f get() = Vec4f(g, r, a, r)
inline val Vec4f.grag: Vec4f get() = Vec4f(g, r, a, g)
inline val Vec4f.graa: Vec4f get() = Vec4f(g, r, a, a)
inline val Vec4f.ggrr: Vec4f get() = Vec4f(g, g, r, r)
inline val Vec4f.ggrg: Vec4f get() = Vec4f(g, g, r, g)
inline val Vec4f.ggrb: Vec4f get() = Vec4f(g, g, r, b)
inline val Vec4f.ggra: Vec4f get() = Vec4f(g, g, r, a)
inline val Vec4f.gggr: Vec4f get() = Vec4f(g, g, g, r)
inline val Vec4f.gggg: Vec4f get() = Vec4f(g, g, g, g)
inline val Vec4f.gggb: Vec4f get() = Vec4f(g, g, g, b)
inline val Vec4f.ggga: Vec4f get() = Vec4f(g, g, g, a)
inline val Vec4f.ggbr: Vec4f get() = Vec4f(g, g, b, r)
inline val Vec4f.ggbg: Vec4f get() = Vec4f(g, g, b, g)
inline val Vec4f.ggbb: Vec4f get() = Vec4f(g, g, b, b)
inline val Vec4f.ggba: Vec4f get() = Vec4f(g, g, b, a)
inline val Vec4f.ggar: Vec4f get() = Vec4f(g, g, a, r)
inline val Vec4f.ggag: Vec4f get() = Vec4f(g, g, a, g)
inline val Vec4f.ggab: Vec4f get() = Vec4f(g, g, a, b)
inline val Vec4f.ggaa: Vec4f get() = Vec4f(g, g, a, a)
inline val Vec4f.gbrr: Vec4f get() = Vec4f(g, b, r, r)
inline val Vec4f.gbrg: Vec4f get() = Vec4f(g, b, r, g)
inline val Vec4f.gbrb: Vec4f get() = Vec4f(g, b, r, b)
inline val Vec4f.gbgr: Vec4f get() = Vec4f(g, b, g, r)
inline val Vec4f.gbgg: Vec4f get() = Vec4f(g, b, g, g)
inline val Vec4f.gbgb: Vec4f get() = Vec4f(g, b, g, b)
inline val Vec4f.gbga: Vec4f get() = Vec4f(g, b, g, a)
inline val Vec4f.gbbr: Vec4f get() = Vec4f(g, b, b, r)
inline val Vec4f.gbbg: Vec4f get() = Vec4f(g, b, b, g)
inline val Vec4f.gbbb: Vec4f get() = Vec4f(g, b, b, b)
inline val Vec4f.gbba: Vec4f get() = Vec4f(g, b, b, a)
inline val Vec4f.gbag: Vec4f get() = Vec4f(g, b, a, g)
inline val Vec4f.gbab: Vec4f get() = Vec4f(g, b, a, b)
inline val Vec4f.gbaa: Vec4f get() = Vec4f(g, b, a, a)
inline val Vec4f.garr: Vec4f get() = Vec4f(g, a, r, r)
inline val Vec4f.garg: Vec4f get() = Vec4f(g, a, r, g)
inline val Vec4f.gara: Vec4f get() = Vec4f(g, a, r, a)
inline val Vec4f.gagr: Vec4f get() = Vec4f(g, a, g, r)
inline val Vec4f.gagg: Vec4f get() = Vec4f(g, a, g, g)
inline val Vec4f.gagb: Vec4f get() = Vec4f(g, a, g, b)
inline val Vec4f.gaga: Vec4f get() = Vec4f(g, a, g, a)
inline val Vec4f.gabg: Vec4f get() = Vec4f(g, a, b, g)
inline val Vec4f.gabb: Vec4f get() = Vec4f(g, a, b, b)
inline val Vec4f.gaba: Vec4f get() = Vec4f(g, a, b, a)
inline val Vec4f.gaar: Vec4f get() = Vec4f(g, a, a, r)
inline val Vec4f.gaag: Vec4f get() = Vec4f(g, a, a, g)
inline val Vec4f.gaab: Vec4f get() = Vec4f(g, a, a, b)
inline val Vec4f.gaaa: Vec4f get() = Vec4f(g, a, a, a)
inline val Vec4f.brrr: Vec4f get() = Vec4f(b, r, r, r)
inline val Vec4f.brrg: Vec4f get() = Vec4f(b, r, r, g)
inline val Vec4f.brrb: Vec4f get() = Vec4f(b, r, r, b)
inline val Vec4f.brra: Vec4f get() = Vec4f(b, r, r, a)
inline val Vec4f.brgr: Vec4f get() = Vec4f(b, r, g, r)
inline val Vec4f.brgg: Vec4f get() = Vec4f(b, r, g, g)
inline val Vec4f.brgb: Vec4f get() = Vec4f(b, r, g, b)
inline val Vec4f.brbr: Vec4f get() = Vec4f(b, r, b, r)
inline val Vec4f.brbg: Vec4f get() = Vec4f(b, r, b, g)
inline val Vec4f.brbb: Vec4f get() = Vec4f(b, r, b, b)
inline val Vec4f.brba: Vec4f get() = Vec4f(b, r, b, a)
inline val Vec4f.brar: Vec4f get() = Vec4f(b, r, a, r)
inline val Vec4f.brab: Vec4f get() = Vec4f(b, r, a, b)
inline val Vec4f.braa: Vec4f get() = Vec4f(b, r, a, a)
inline val Vec4f.bgrr: Vec4f get() = Vec4f(b, g, r, r)
inline val Vec4f.bgrg: Vec4f get() = Vec4f(b, g, r, g)
inline val Vec4f.bgrb: Vec4f get() = Vec4f(b, g, r, b)
inline val Vec4f.bggr: Vec4f get() = Vec4f(b, g, g, r)
inline val Vec4f.bggg: Vec4f get() = Vec4f(b, g, g, g)
inline val Vec4f.bggb: Vec4f get() = Vec4f(b, g, g, b)
inline val Vec4f.bgga: Vec4f get() = Vec4f(b, g, g, a)
inline val Vec4f.bgbr: Vec4f get() = Vec4f(b, g, b, r)
inline val Vec4f.bgbg: Vec4f get() = Vec4f(b, g, b, g)
inline val Vec4f.bgbb: Vec4f get() = Vec4f(b, g, b, b)
inline val Vec4f.bgba: Vec4f get() = Vec4f(b, g, b, a)
inline val Vec4f.bgag: Vec4f get() = Vec4f(b, g, a, g)
inline val Vec4f.bgab: Vec4f get() = Vec4f(b, g, a, b)
inline val Vec4f.bgaa: Vec4f get() = Vec4f(b, g, a, a)
inline val Vec4f.bbrr: Vec4f get() = Vec4f(b, b, r, r)
inline val Vec4f.bbrg: Vec4f get() = Vec4f(b, b, r, g)
inline val Vec4f.bbrb: Vec4f get() = Vec4f(b, b, r, b)
inline val Vec4f.bbra: Vec4f get() = Vec4f(b, b, r, a)
inline val Vec4f.bbgr: Vec4f get() = Vec4f(b, b, g, r)
inline val Vec4f.bbgg: Vec4f get() = Vec4f(b, b, g, g)
inline val Vec4f.bbgb: Vec4f get() = Vec4f(b, b, g, b)
inline val Vec4f.bbga: Vec4f get() = Vec4f(b, b, g, a)
inline val Vec4f.bbbr: Vec4f get() = Vec4f(b, b, b, r)
inline val Vec4f.bbbg: Vec4f get() = Vec4f(b, b, b, g)
inline val Vec4f.bbbb: Vec4f get() = Vec4f(b, b, b, b)
inline val Vec4f.bbba: Vec4f get() = Vec4f(b, b, b, a)
inline val Vec4f.bbar: Vec4f get() = Vec4f(b, b, a, r)
inline val Vec4f.bbag: Vec4f get() = Vec4f(b, b, a, g)
inline val Vec4f.bbab: Vec4f get() = Vec4f(b, b, a, b)
inline val Vec4f.bbaa: Vec4f get() = Vec4f(b, b, a, a)
inline val Vec4f.barr: Vec4f get() = Vec4f(b, a, r, r)
inline val Vec4f.barb: Vec4f get() = Vec4f(b, a, r, b)
inline val Vec4f.bara: Vec4f get() = Vec4f(b, a, r, a)
inline val Vec4f.bagg: Vec4f get() = Vec4f(b, a, g, g)
inline val Vec4f.bagb: Vec4f get() = Vec4f(b, a, g, b)
inline val Vec4f.baga: Vec4f get() = Vec4f(b, a, g, a)
inline val Vec4f.babr: Vec4f get() = Vec4f(b, a, b, r)
inline val Vec4f.babg: Vec4f get() = Vec4f(b, a, b, g)
inline val Vec4f.babb: Vec4f get() = Vec4f(b, a, b, b)
inline val Vec4f.baba: Vec4f get() = Vec4f(b, a, b, a)
inline val Vec4f.baar: Vec4f get() = Vec4f(b, a, a, r)
inline val Vec4f.baag: Vec4f get() = Vec4f(b, a, a, g)
inline val Vec4f.baab: Vec4f get() = Vec4f(b, a, a, b)
inline val Vec4f.baaa: Vec4f get() = Vec4f(b, a, a, a)
inline val Vec4f.arrr: Vec4f get() = Vec4f(a, r, r, r)
inline val Vec4f.arrg: Vec4f get() = Vec4f(a, r, r, g)
inline val Vec4f.arrb: Vec4f get() = Vec4f(a, r, r, b)
inline val Vec4f.arra: Vec4f get() = Vec4f(a, r, r, a)
inline val Vec4f.argr: Vec4f get() = Vec4f(a, r, g, r)
inline val Vec4f.argg: Vec4f get() = Vec4f(a, r, g, g)
inline val Vec4f.arga: Vec4f get() = Vec4f(a, r, g, a)
inline val Vec4f.arbr: Vec4f get() = Vec4f(a, r, b, r)
inline val Vec4f.arbb: Vec4f get() = Vec4f(a, r, b, b)
inline val Vec4f.arba: Vec4f get() = Vec4f(a, r, b, a)
inline val Vec4f.arar: Vec4f get() = Vec4f(a, r, a, r)
inline val Vec4f.arag: Vec4f get() = Vec4f(a, r, a, g)
inline val Vec4f.arab: Vec4f get() = Vec4f(a, r, a, b)
inline val Vec4f.araa: Vec4f get() = Vec4f(a, r, a, a)
inline val Vec4f.agrr: Vec4f get() = Vec4f(a, g, r, r)
inline val Vec4f.agrg: Vec4f get() = Vec4f(a, g, r, g)
inline val Vec4f.agra: Vec4f get() = Vec4f(a, g, r, a)
inline val Vec4f.aggr: Vec4f get() = Vec4f(a, g, g, r)
inline val Vec4f.aggg: Vec4f get() = Vec4f(a, g, g, g)
inline val Vec4f.aggb: Vec4f get() = Vec4f(a, g, g, b)
inline val Vec4f.agga: Vec4f get() = Vec4f(a, g, g, a)
inline val Vec4f.agbg: Vec4f get() = Vec4f(a, g, b, g)
inline val Vec4f.agbb: Vec4f get() = Vec4f(a, g, b, b)
inline val Vec4f.agba: Vec4f get() = Vec4f(a, g, b, a)
inline val Vec4f.agar: Vec4f get() = Vec4f(a, g, a, r)
inline val Vec4f.agag: Vec4f get() = Vec4f(a, g, a, g)
inline val Vec4f.agab: Vec4f get() = Vec4f(a, g, a, b)
inline val Vec4f.agaa: Vec4f get() = Vec4f(a, g, a, a)
inline val Vec4f.abrr: Vec4f get() = Vec4f(a, b, r, r)
inline val Vec4f.abrb: Vec4f get() = Vec4f(a, b, r, b)
inline val Vec4f.abra: Vec4f get() = Vec4f(a, b, r, a)
inline val Vec4f.abgg: Vec4f get() = Vec4f(a, b, g, g)
inline val Vec4f.abgb: Vec4f get() = Vec4f(a, b, g, b)
inline val Vec4f.abga: Vec4f get() = Vec4f(a, b, g, a)
inline val Vec4f.abbr: Vec4f get() = Vec4f(a, b, b, r)
inline val Vec4f.abbg: Vec4f get() = Vec4f(a, b, b, g)
inline val Vec4f.abbb: Vec4f get() = Vec4f(a, b, b, b)
inline val Vec4f.abba: Vec4f get() = Vec4f(a, b, b, a)
inline val Vec4f.abar: Vec4f get() = Vec4f(a, b, a, r)
inline val Vec4f.abag: Vec4f get() = Vec4f(a, b, a, g)
inline val Vec4f.abab: Vec4f get() = Vec4f(a, b, a, b)
inline val Vec4f.abaa: Vec4f get() = Vec4f(a, b, a, a)
inline val Vec4f.aarr: Vec4f get() = Vec4f(a, a, r, r)
inline val Vec4f.aarg: Vec4f get() = Vec4f(a, a, r, g)
inline val Vec4f.aarb: Vec4f get() = Vec4f(a, a, r, b)
inline val Vec4f.aara: Vec4f get() = Vec4f(a, a, r, a)
inline val Vec4f.aagr: Vec4f get() = Vec4f(a, a, g, r)
inline val Vec4f.aagg: Vec4f get() = Vec4f(a, a, g, g)
inline val Vec4f.aagb: Vec4f get() = Vec4f(a, a, g, b)
inline val Vec4f.aaga: Vec4f get() = Vec4f(a, a, g, a)
inline val Vec4f.aabr: Vec4f get() = Vec4f(a, a, b, r)
inline val Vec4f.aabg: Vec4f get() = Vec4f(a, a, b, g)
inline val Vec4f.aabb: Vec4f get() = Vec4f(a, a, b, b)
inline val Vec4f.aaba: Vec4f get() = Vec4f(a, a, b, a)
inline val Vec4f.aaar: Vec4f get() = Vec4f(a, a, a, r)
inline val Vec4f.aaag: Vec4f get() = Vec4f(a, a, a, g)
inline val Vec4f.aaab: Vec4f get() = Vec4f(a, a, a, b)
inline val Vec4f.aaaa: Vec4f get() = Vec4f(a, a, a, a)

// Vec2f non-duplicate l-value swizzling st
inline var Vec2f.st: Vec2f get() = Vec2f(s, t); set(value) { s = value.s; t = value.t }
inline var Vec2f.ts: Vec2f get() = Vec2f(t, s); set(value) { t = value.s; s = value.t }

// Vec2f duplicate l-value swizzling st
inline val Vec2f.ss:   Vec2f get() = Vec2f(s, s)
inline val Vec2f.tt:   Vec2f get() = Vec2f(t, t)
inline val Vec2f.ttt:  Vec3f get() = Vec3f(t, t, t)
inline val Vec2f.tts:  Vec3f get() = Vec3f(t, t, s)
inline val Vec2f.tst:  Vec3f get() = Vec3f(t, s, t)
inline val Vec2f.tss:  Vec3f get() = Vec3f(t, s, s)
inline val Vec2f.stt:  Vec3f get() = Vec3f(s, t, t)
inline val Vec2f.sts:  Vec3f get() = Vec3f(s, t, s)
inline val Vec2f.sst:  Vec3f get() = Vec3f(s, s, t)
inline val Vec2f.sss:  Vec3f get() = Vec3f(s, s, s)
inline val Vec2f.tttt: Vec4f get() = Vec4f(t, t, t, t)
inline val Vec2f.ttts: Vec4f get() = Vec4f(t, t, t, s)
inline val Vec2f.ttst: Vec4f get() = Vec4f(t, t, s, t)
inline val Vec2f.ttss: Vec4f get() = Vec4f(t, t, s, s)
inline val Vec2f.tstt: Vec4f get() = Vec4f(t, s, t, t)
inline val Vec2f.tsts: Vec4f get() = Vec4f(t, s, t, s)
inline val Vec2f.tsst: Vec4f get() = Vec4f(t, s, s, t)
inline val Vec2f.tsss: Vec4f get() = Vec4f(t, s, s, s)
inline val Vec2f.sttt: Vec4f get() = Vec4f(s, t, t, t)
inline val Vec2f.stts: Vec4f get() = Vec4f(s, t, t, s)
inline val Vec2f.stst: Vec4f get() = Vec4f(s, t, s, t)
inline val Vec2f.stss: Vec4f get() = Vec4f(s, t, s, s)
inline val Vec2f.sstt: Vec4f get() = Vec4f(s, s, t, t)
inline val Vec2f.ssts: Vec4f get() = Vec4f(s, s, t, s)
inline val Vec2f.ssst: Vec4f get() = Vec4f(s, s, s, t)
inline val Vec2f.ssss: Vec4f get() = Vec4f(s, s, s, s)

// Vec3f non-duplicate l-value swizzling stp
inline var Vec3f.st:  Vec2f get() = Vec2f(s, t);    set(value) { s = value.s; t = value.t }
inline var Vec3f.ts:  Vec2f get() = Vec2f(t, s);    set(value) { t = value.s; s = value.t }
inline var Vec3f.pt:  Vec2f get() = Vec2f(p, t);    set(value) { p = value.s; t = value.t }
inline var Vec3f.tp:  Vec2f get() = Vec2f(t, p);    set(value) { t = value.s; p = value.t }
inline var Vec3f.sp:  Vec2f get() = Vec2f(s, p);    set(value) { s = value.s; p = value.t }
inline var Vec3f.ps:  Vec2f get() = Vec2f(p, s);    set(value) { p = value.s; s = value.t }
inline var Vec3f.pst: Vec3f get() = Vec3f(p, s, t); set(value) { p = value.s; s = value.t; t = value.p }
inline var Vec3f.pts: Vec3f get() = Vec3f(p, t, s); set(value) { p = value.s; t = value.t; s = value.p }
inline var Vec3f.spt: Vec3f get() = Vec3f(s, p, t); set(value) { s = value.s; p = value.t; t = value.p }
inline var Vec3f.stp: Vec3f get() = Vec3f(s, t, p); set(value) { s = value.s; t = value.t; p = value.p }
inline var Vec3f.tsp: Vec3f get() = Vec3f(t, s, p); set(value) { t = value.s; s = value.t; p = value.p }
inline var Vec3f.tps: Vec3f get() = Vec3f(t, p, s); set(value) { t = value.s; p = value.t; s = value.p }

// Vec3f duplicate l-value swizzling stp
inline val Vec3f.ss:   Vec2f get() = Vec2f(s, s)
inline val Vec3f.tt:   Vec2f get() = Vec2f(t, t)
inline val Vec3f.pp:   Vec2f get() = Vec2f(p, p)
inline val Vec3f.ppp:  Vec3f get() = Vec3f(p, p, p)
inline val Vec3f.ppt:  Vec3f get() = Vec3f(p, p, t)
inline val Vec3f.pps:  Vec3f get() = Vec3f(p, p, s)
inline val Vec3f.ptp:  Vec3f get() = Vec3f(p, t, p)
inline val Vec3f.ptt:  Vec3f get() = Vec3f(p, t, t)
inline val Vec3f.psp:  Vec3f get() = Vec3f(p, s, p)
inline val Vec3f.pss:  Vec3f get() = Vec3f(p, s, s)
inline val Vec3f.tpp:  Vec3f get() = Vec3f(t, p, p)
inline val Vec3f.tpt:  Vec3f get() = Vec3f(t, p, t)
inline val Vec3f.ttp:  Vec3f get() = Vec3f(t, t, p)
inline val Vec3f.ttt:  Vec3f get() = Vec3f(t, t, t)
inline val Vec3f.tts:  Vec3f get() = Vec3f(t, t, s)
inline val Vec3f.tst:  Vec3f get() = Vec3f(t, s, t)
inline val Vec3f.tss:  Vec3f get() = Vec3f(t, s, s)
inline val Vec3f.spp:  Vec3f get() = Vec3f(s, p, p)
inline val Vec3f.sps:  Vec3f get() = Vec3f(s, p, s)
inline val Vec3f.stt:  Vec3f get() = Vec3f(s, t, t)
inline val Vec3f.sts:  Vec3f get() = Vec3f(s, t, s)
inline val Vec3f.ssp:  Vec3f get() = Vec3f(s, s, p)
inline val Vec3f.sst:  Vec3f get() = Vec3f(s, s, t)
inline val Vec3f.sss:  Vec3f get() = Vec3f(s, s, s)
inline val Vec3f.pppp: Vec4f get() = Vec4f(p, p, p, p)
inline val Vec3f.pppt: Vec4f get() = Vec4f(p, p, p, t)
inline val Vec3f.ppps: Vec4f get() = Vec4f(p, p, p, s)
inline val Vec3f.pptp: Vec4f get() = Vec4f(p, p, t, p)
inline val Vec3f.pptt: Vec4f get() = Vec4f(p, p, t, t)
inline val Vec3f.ppts: Vec4f get() = Vec4f(p, p, t, s)
inline val Vec3f.ppsp: Vec4f get() = Vec4f(p, p, s, p)
inline val Vec3f.ppst: Vec4f get() = Vec4f(p, p, s, t)
inline val Vec3f.ppss: Vec4f get() = Vec4f(p, p, s, s)
inline val Vec3f.ptpp: Vec4f get() = Vec4f(p, t, p, p)
inline val Vec3f.ptpt: Vec4f get() = Vec4f(p, t, p, t)
inline val Vec3f.ptps: Vec4f get() = Vec4f(p, t, p, s)
inline val Vec3f.pttp: Vec4f get() = Vec4f(p, t, t, p)
inline val Vec3f.pttt: Vec4f get() = Vec4f(p, t, t, t)
inline val Vec3f.ptts: Vec4f get() = Vec4f(p, t, t, s)
inline val Vec3f.ptsp: Vec4f get() = Vec4f(p, t, s, p)
inline val Vec3f.ptst: Vec4f get() = Vec4f(p, t, s, t)
inline val Vec3f.ptss: Vec4f get() = Vec4f(p, t, s, s)
inline val Vec3f.pspp: Vec4f get() = Vec4f(p, s, p, p)
inline val Vec3f.pspt: Vec4f get() = Vec4f(p, s, p, t)
inline val Vec3f.psps: Vec4f get() = Vec4f(p, s, p, s)
inline val Vec3f.pstp: Vec4f get() = Vec4f(p, s, t, p)
inline val Vec3f.pstt: Vec4f get() = Vec4f(p, s, t, t)
inline val Vec3f.psts: Vec4f get() = Vec4f(p, s, t, s)
inline val Vec3f.pssp: Vec4f get() = Vec4f(p, s, s, p)
inline val Vec3f.psst: Vec4f get() = Vec4f(p, s, s, t)
inline val Vec3f.psss: Vec4f get() = Vec4f(p, s, s, s)
inline val Vec3f.tppp: Vec4f get() = Vec4f(t, p, p, p)
inline val Vec3f.tppt: Vec4f get() = Vec4f(t, p, p, t)
inline val Vec3f.tpps: Vec4f get() = Vec4f(t, p, p, s)
inline val Vec3f.tptp: Vec4f get() = Vec4f(t, p, t, p)
inline val Vec3f.tptt: Vec4f get() = Vec4f(t, p, t, t)
inline val Vec3f.tpts: Vec4f get() = Vec4f(t, p, t, s)
inline val Vec3f.tpsp: Vec4f get() = Vec4f(t, p, s, p)
inline val Vec3f.tpst: Vec4f get() = Vec4f(t, p, s, t)
inline val Vec3f.tpss: Vec4f get() = Vec4f(t, p, s, s)
inline val Vec3f.ttpp: Vec4f get() = Vec4f(t, t, p, p)
inline val Vec3f.ttpt: Vec4f get() = Vec4f(t, t, p, t)
inline val Vec3f.ttps: Vec4f get() = Vec4f(t, t, p, s)
inline val Vec3f.tttp: Vec4f get() = Vec4f(t, t, t, p)
inline val Vec3f.tttt: Vec4f get() = Vec4f(t, t, t, t)
inline val Vec3f.ttts: Vec4f get() = Vec4f(t, t, t, s)
inline val Vec3f.ttsp: Vec4f get() = Vec4f(t, t, s, p)
inline val Vec3f.ttst: Vec4f get() = Vec4f(t, t, s, t)
inline val Vec3f.ttss: Vec4f get() = Vec4f(t, t, s, s)
inline val Vec3f.tspp: Vec4f get() = Vec4f(t, s, p, p)
inline val Vec3f.tspt: Vec4f get() = Vec4f(t, s, p, t)
inline val Vec3f.tsps: Vec4f get() = Vec4f(t, s, p, s)
inline val Vec3f.tstp: Vec4f get() = Vec4f(t, s, t, p)
inline val Vec3f.tstt: Vec4f get() = Vec4f(t, s, t, t)
inline val Vec3f.tsts: Vec4f get() = Vec4f(t, s, t, s)
inline val Vec3f.tssp: Vec4f get() = Vec4f(t, s, s, p)
inline val Vec3f.tsst: Vec4f get() = Vec4f(t, s, s, t)
inline val Vec3f.tsss: Vec4f get() = Vec4f(t, s, s, s)
inline val Vec3f.sppp: Vec4f get() = Vec4f(s, p, p, p)
inline val Vec3f.sppt: Vec4f get() = Vec4f(s, p, p, t)
inline val Vec3f.spps: Vec4f get() = Vec4f(s, p, p, s)
inline val Vec3f.sptp: Vec4f get() = Vec4f(s, p, t, p)
inline val Vec3f.sptt: Vec4f get() = Vec4f(s, p, t, t)
inline val Vec3f.spts: Vec4f get() = Vec4f(s, p, t, s)
inline val Vec3f.spsp: Vec4f get() = Vec4f(s, p, s, p)
inline val Vec3f.spst: Vec4f get() = Vec4f(s, p, s, t)
inline val Vec3f.spss: Vec4f get() = Vec4f(s, p, s, s)
inline val Vec3f.stpp: Vec4f get() = Vec4f(s, t, p, p)
inline val Vec3f.stpt: Vec4f get() = Vec4f(s, t, p, t)
inline val Vec3f.stps: Vec4f get() = Vec4f(s, t, p, s)
inline val Vec3f.sttp: Vec4f get() = Vec4f(s, t, t, p)
inline val Vec3f.sttt: Vec4f get() = Vec4f(s, t, t, t)
inline val Vec3f.stts: Vec4f get() = Vec4f(s, t, t, s)
inline val Vec3f.stsp: Vec4f get() = Vec4f(s, t, s, p)
inline val Vec3f.stst: Vec4f get() = Vec4f(s, t, s, t)
inline val Vec3f.stss: Vec4f get() = Vec4f(s, t, s, s)
inline val Vec3f.sspp: Vec4f get() = Vec4f(s, s, p, p)
inline val Vec3f.sspt: Vec4f get() = Vec4f(s, s, p, t)
inline val Vec3f.ssps: Vec4f get() = Vec4f(s, s, p, s)
inline val Vec3f.sstp: Vec4f get() = Vec4f(s, s, t, p)
inline val Vec3f.sstt: Vec4f get() = Vec4f(s, s, t, t)
inline val Vec3f.ssts: Vec4f get() = Vec4f(s, s, t, s)
inline val Vec3f.sssp: Vec4f get() = Vec4f(s, s, s, p)
inline val Vec3f.ssst: Vec4f get() = Vec4f(s, s, s, t)
inline val Vec3f.ssss: Vec4f get() = Vec4f(s, s, s, s)

// Vec4f non-duplicate l-value swizzling stpq
inline var Vec4f.st:   Vec2f get() = Vec2f(s, t);       set(value) { s = value.s; t = value.t }
inline var Vec4f.sp:   Vec2f get() = Vec2f(s, p);       set(value) { s = value.s; p = value.t }
inline var Vec4f.sq:   Vec2f get() = Vec2f(s, q);       set(value) { s = value.s; q = value.t }
inline var Vec4f.ts:   Vec2f get() = Vec2f(t, s);       set(value) { t = value.s; s = value.t }
inline var Vec4f.tp:   Vec2f get() = Vec2f(t, p);       set(value) { t = value.s; p = value.t }
inline var Vec4f.tq:   Vec2f get() = Vec2f(t, q);       set(value) { t = value.s; q = value.t }
inline var Vec4f.ps:   Vec2f get() = Vec2f(p, s);       set(value) { p = value.s; s = value.t }
inline var Vec4f.pt:   Vec2f get() = Vec2f(p, t);       set(value) { p = value.s; t = value.t }
inline var Vec4f.pq:   Vec2f get() = Vec2f(p, q);       set(value) { p = value.s; q = value.t }
inline var Vec4f.qs:   Vec2f get() = Vec2f(q, s);       set(value) { q = value.s; s = value.t }
inline var Vec4f.qt:   Vec2f get() = Vec2f(q, t);       set(value) { q = value.s; t = value.t }
inline var Vec4f.qp:   Vec2f get() = Vec2f(q, p);       set(value) { q = value.s; p = value.t }
inline var Vec4f.stp:  Vec3f get() = Vec3f(s, t, p);    set(value) { s = value.s; t = value.t; p = value.p }
inline var Vec4f.stq:  Vec3f get() = Vec3f(s, t, q);    set(value) { s = value.s; t = value.t; q = value.p }
inline var Vec4f.spt:  Vec3f get() = Vec3f(s, p, t);    set(value) { s = value.s; p = value.t; t = value.p }
inline var Vec4f.spq:  Vec3f get() = Vec3f(s, p, q);    set(value) { s = value.s; p = value.t; q = value.p }
inline var Vec4f.sqt:  Vec3f get() = Vec3f(s, q, t);    set(value) { s = value.s; q = value.t; t = value.p }
inline var Vec4f.sqp:  Vec3f get() = Vec3f(s, q, p);    set(value) { s = value.s; q = value.t; p = value.p }
inline var Vec4f.tsp:  Vec3f get() = Vec3f(t, s, p);    set(value) { t = value.s; s = value.t; p = value.p }
inline var Vec4f.tsq:  Vec3f get() = Vec3f(t, s, q);    set(value) { t = value.s; s = value.t; q = value.p }
inline var Vec4f.tps:  Vec3f get() = Vec3f(t, p, s);    set(value) { t = value.s; p = value.t; s = value.p }
inline var Vec4f.tpq:  Vec3f get() = Vec3f(t, p, q);    set(value) { t = value.s; p = value.t; q = value.p }
inline var Vec4f.tqs:  Vec3f get() = Vec3f(t, q, s);    set(value) { t = value.s; q = value.t; s = value.p }
inline var Vec4f.tqp:  Vec3f get() = Vec3f(t, q, p);    set(value) { t = value.s; q = value.t; p = value.p }
inline var Vec4f.pst:  Vec3f get() = Vec3f(p, s, t);    set(value) { p = value.s; s = value.t; t = value.p }
inline var Vec4f.psq:  Vec3f get() = Vec3f(p, s, q);    set(value) { p = value.s; s = value.t; q = value.p }
inline var Vec4f.pts:  Vec3f get() = Vec3f(p, t, s);    set(value) { p = value.s; t = value.t; s = value.p }
inline var Vec4f.ptq:  Vec3f get() = Vec3f(p, t, q);    set(value) { p = value.s; t = value.t; q = value.p }
inline var Vec4f.pqs:  Vec3f get() = Vec3f(p, q, s);    set(value) { p = value.s; q = value.t; s = value.p }
inline var Vec4f.pqt:  Vec3f get() = Vec3f(p, q, t);    set(value) { p = value.s; q = value.t; t = value.p }
inline var Vec4f.qst:  Vec3f get() = Vec3f(q, s, t);    set(value) { q = value.s; s = value.t; t = value.p }
inline var Vec4f.qsp:  Vec3f get() = Vec3f(q, s, p);    set(value) { q = value.s; s = value.t; p = value.p }
inline var Vec4f.qts:  Vec3f get() = Vec3f(q, t, s);    set(value) { q = value.s; t = value.t; s = value.p }
inline var Vec4f.qtp:  Vec3f get() = Vec3f(q, t, p);    set(value) { q = value.s; t = value.t; p = value.p }
inline var Vec4f.qps:  Vec3f get() = Vec3f(q, p, s);    set(value) { q = value.s; p = value.t; s = value.p }
inline var Vec4f.qpt:  Vec3f get() = Vec3f(q, p, t);    set(value) { q = value.s; p = value.t; t = value.p }
inline var Vec4f.stpq: Vec4f get() = Vec4f(s, t, p, q); set(value) { s = value.s; t = value.t; p = value.p; q = value.q }
inline var Vec4f.stqp: Vec4f get() = Vec4f(s, t, q, p); set(value) { s = value.s; t = value.t; q = value.p; p = value.q }
inline var Vec4f.sptq: Vec4f get() = Vec4f(s, p, t, q); set(value) { s = value.s; p = value.t; t = value.p; q = value.q }
inline var Vec4f.spqt: Vec4f get() = Vec4f(s, p, q, t); set(value) { s = value.s; p = value.t; q = value.p; t = value.q }
inline var Vec4f.sqtp: Vec4f get() = Vec4f(s, q, t, p); set(value) { s = value.s; q = value.t; t = value.p; p = value.q }
inline var Vec4f.sqpt: Vec4f get() = Vec4f(s, q, p, t); set(value) { s = value.s; q = value.t; p = value.p; t = value.q }
inline var Vec4f.tspq: Vec4f get() = Vec4f(t, s, p, q); set(value) { t = value.s; s = value.t; p = value.p; q = value.q }
inline var Vec4f.tsqp: Vec4f get() = Vec4f(t, s, q, p); set(value) { t = value.s; s = value.t; q = value.p; p = value.q }
inline var Vec4f.tpsq: Vec4f get() = Vec4f(t, p, s, q); set(value) { t = value.s; p = value.t; s = value.p; q = value.q }
inline var Vec4f.tpqs: Vec4f get() = Vec4f(t, p, q, s); set(value) { t = value.s; p = value.t; q = value.p; s = value.q }
inline var Vec4f.tqsp: Vec4f get() = Vec4f(t, q, s, p); set(value) { t = value.s; q = value.t; s = value.p; p = value.q }
inline var Vec4f.tqps: Vec4f get() = Vec4f(t, q, p, s); set(value) { t = value.s; q = value.t; p = value.p; s = value.q }
inline var Vec4f.pstq: Vec4f get() = Vec4f(p, s, t, q); set(value) { p = value.s; s = value.t; t = value.p; q = value.q }
inline var Vec4f.psqt: Vec4f get() = Vec4f(p, s, q, t); set(value) { p = value.s; s = value.t; q = value.p; t = value.q }
inline var Vec4f.ptsq: Vec4f get() = Vec4f(p, t, s, q); set(value) { p = value.s; t = value.t; s = value.p; q = value.q }
inline var Vec4f.ptqs: Vec4f get() = Vec4f(p, t, q, s); set(value) { p = value.s; t = value.t; q = value.p; s = value.q }
inline var Vec4f.pqst: Vec4f get() = Vec4f(p, q, s, t); set(value) { p = value.s; q = value.t; s = value.p; t = value.q }
inline var Vec4f.pqts: Vec4f get() = Vec4f(p, q, t, s); set(value) { p = value.s; q = value.t; t = value.p; s = value.q }
inline var Vec4f.qstp: Vec4f get() = Vec4f(q, s, t, p); set(value) { q = value.s; s = value.t; t = value.p; p = value.q }
inline var Vec4f.qspt: Vec4f get() = Vec4f(q, s, p, t); set(value) { q = value.s; s = value.t; p = value.p; t = value.q }
inline var Vec4f.qtsp: Vec4f get() = Vec4f(q, t, s, p); set(value) { q = value.s; t = value.t; s = value.p; p = value.q }
inline var Vec4f.qtps: Vec4f get() = Vec4f(q, t, p, s); set(value) { q = value.s; t = value.t; p = value.p; s = value.q }
inline var Vec4f.qpst: Vec4f get() = Vec4f(q, p, s, t); set(value) { q = value.s; p = value.t; s = value.p; t = value.q }
inline var Vec4f.qpts: Vec4f get() = Vec4f(q, p, t, s); set(value) { q = value.s; p = value.t; t = value.p; s = value.q }

// Vec4f duplicate l-value swizzling stpq
inline val Vec4f.ss: Vec2f get() = Vec2f(s, s)
inline val Vec4f.tt: Vec2f get() = Vec2f(s, s)
inline val Vec4f.pp: Vec2f get() = Vec2f(s, s)
inline val Vec4f.qq: Vec2f get() = Vec2f(s, s)
inline val Vec4f.sss: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.sst: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ssp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ssq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.sts: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.stt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.sps: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.spp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.sqs: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.sqq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tss: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tst: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tts: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ttt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ttp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ttq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tpt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tpp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tqt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.tqq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.pss: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.psp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ptt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ptp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.pps: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ppt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ppp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ppq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.pqp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.pqq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qss: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qsq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qtt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qtq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qpp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qpq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qqs: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qqt: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qqp: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.qqq: Vec3f get() = Vec3f(s, s, s)
inline val Vec4f.ssss: Vec4f get() = Vec4f(s, s, s, s)
inline val Vec4f.ssst: Vec4f get() = Vec4f(s, s, s, t)
inline val Vec4f.sssp: Vec4f get() = Vec4f(s, s, s, p)
inline val Vec4f.sssq: Vec4f get() = Vec4f(s, s, s, q)
inline val Vec4f.ssts: Vec4f get() = Vec4f(s, s, t, s)
inline val Vec4f.sstt: Vec4f get() = Vec4f(s, s, t, t)
inline val Vec4f.sstp: Vec4f get() = Vec4f(s, s, t, p)
inline val Vec4f.sstq: Vec4f get() = Vec4f(s, s, t, q)
inline val Vec4f.ssps: Vec4f get() = Vec4f(s, s, p, s)
inline val Vec4f.sspt: Vec4f get() = Vec4f(s, s, p, t)
inline val Vec4f.sspp: Vec4f get() = Vec4f(s, s, p, p)
inline val Vec4f.sspq: Vec4f get() = Vec4f(s, s, p, q)
inline val Vec4f.ssqs: Vec4f get() = Vec4f(s, s, q, s)
inline val Vec4f.ssqt: Vec4f get() = Vec4f(s, s, q, t)
inline val Vec4f.ssqp: Vec4f get() = Vec4f(s, s, q, p)
inline val Vec4f.ssqq: Vec4f get() = Vec4f(s, s, q, q)
inline val Vec4f.stss: Vec4f get() = Vec4f(s, t, s, s)
inline val Vec4f.stst: Vec4f get() = Vec4f(s, t, s, t)
inline val Vec4f.stsp: Vec4f get() = Vec4f(s, t, s, p)
inline val Vec4f.stsq: Vec4f get() = Vec4f(s, t, s, q)
inline val Vec4f.stts: Vec4f get() = Vec4f(s, t, t, s)
inline val Vec4f.sttt: Vec4f get() = Vec4f(s, t, t, t)
inline val Vec4f.sttp: Vec4f get() = Vec4f(s, t, t, p)
inline val Vec4f.sttq: Vec4f get() = Vec4f(s, t, t, q)
inline val Vec4f.stps: Vec4f get() = Vec4f(s, t, p, s)
inline val Vec4f.stpt: Vec4f get() = Vec4f(s, t, p, t)
inline val Vec4f.stpp: Vec4f get() = Vec4f(s, t, p, p)
inline val Vec4f.stqs: Vec4f get() = Vec4f(s, t, q, s)
inline val Vec4f.stqt: Vec4f get() = Vec4f(s, t, q, t)
inline val Vec4f.stqq: Vec4f get() = Vec4f(s, t, q, q)
inline val Vec4f.spss: Vec4f get() = Vec4f(s, p, s, s)
inline val Vec4f.spst: Vec4f get() = Vec4f(s, p, s, t)
inline val Vec4f.spsp: Vec4f get() = Vec4f(s, p, s, p)
inline val Vec4f.spsq: Vec4f get() = Vec4f(s, p, s, q)
inline val Vec4f.spts: Vec4f get() = Vec4f(s, p, t, s)
inline val Vec4f.sptt: Vec4f get() = Vec4f(s, p, t, t)
inline val Vec4f.sptp: Vec4f get() = Vec4f(s, p, t, p)
inline val Vec4f.spps: Vec4f get() = Vec4f(s, p, p, s)
inline val Vec4f.sppt: Vec4f get() = Vec4f(s, p, p, t)
inline val Vec4f.sppp: Vec4f get() = Vec4f(s, p, p, p)
inline val Vec4f.sppq: Vec4f get() = Vec4f(s, p, p, q)
inline val Vec4f.spqs: Vec4f get() = Vec4f(s, p, q, s)
inline val Vec4f.spqp: Vec4f get() = Vec4f(s, p, q, p)
inline val Vec4f.spqq: Vec4f get() = Vec4f(s, p, q, q)
inline val Vec4f.sqss: Vec4f get() = Vec4f(s, q, s, s)
inline val Vec4f.sqst: Vec4f get() = Vec4f(s, q, s, t)
inline val Vec4f.sqsp: Vec4f get() = Vec4f(s, q, s, p)
inline val Vec4f.sqsq: Vec4f get() = Vec4f(s, q, s, q)
inline val Vec4f.sqts: Vec4f get() = Vec4f(s, q, t, s)
inline val Vec4f.sqtt: Vec4f get() = Vec4f(s, q, t, t)
inline val Vec4f.sqtq: Vec4f get() = Vec4f(s, q, t, q)
inline val Vec4f.sqps: Vec4f get() = Vec4f(s, q, p, s)
inline val Vec4f.sqpp: Vec4f get() = Vec4f(s, q, p, p)
inline val Vec4f.sqpq: Vec4f get() = Vec4f(s, q, p, q)
inline val Vec4f.sqqs: Vec4f get() = Vec4f(s, q, q, s)
inline val Vec4f.sqqt: Vec4f get() = Vec4f(s, q, q, t)
inline val Vec4f.sqqp: Vec4f get() = Vec4f(s, q, q, p)
inline val Vec4f.sqqq: Vec4f get() = Vec4f(s, q, q, q)
inline val Vec4f.tsss: Vec4f get() = Vec4f(t, s, s, s)
inline val Vec4f.tsst: Vec4f get() = Vec4f(t, s, s, t)
inline val Vec4f.tssp: Vec4f get() = Vec4f(t, s, s, p)
inline val Vec4f.tssq: Vec4f get() = Vec4f(t, s, s, q)
inline val Vec4f.tsts: Vec4f get() = Vec4f(t, s, t, s)
inline val Vec4f.tstt: Vec4f get() = Vec4f(t, s, t, t)
inline val Vec4f.tstp: Vec4f get() = Vec4f(t, s, t, p)
inline val Vec4f.tstq: Vec4f get() = Vec4f(t, s, t, q)
inline val Vec4f.tsps: Vec4f get() = Vec4f(t, s, p, s)
inline val Vec4f.tspt: Vec4f get() = Vec4f(t, s, p, t)
inline val Vec4f.tspp: Vec4f get() = Vec4f(t, s, p, p)
inline val Vec4f.tsqs: Vec4f get() = Vec4f(t, s, q, s)
inline val Vec4f.tsqt: Vec4f get() = Vec4f(t, s, q, t)
inline val Vec4f.tsqq: Vec4f get() = Vec4f(t, s, q, q)
inline val Vec4f.ttss: Vec4f get() = Vec4f(t, t, s, s)
inline val Vec4f.ttst: Vec4f get() = Vec4f(t, t, s, t)
inline val Vec4f.ttsp: Vec4f get() = Vec4f(t, t, s, p)
inline val Vec4f.ttsq: Vec4f get() = Vec4f(t, t, s, q)
inline val Vec4f.ttts: Vec4f get() = Vec4f(t, t, t, s)
inline val Vec4f.tttt: Vec4f get() = Vec4f(t, t, t, t)
inline val Vec4f.tttp: Vec4f get() = Vec4f(t, t, t, p)
inline val Vec4f.tttq: Vec4f get() = Vec4f(t, t, t, q)
inline val Vec4f.ttps: Vec4f get() = Vec4f(t, t, p, s)
inline val Vec4f.ttpt: Vec4f get() = Vec4f(t, t, p, t)
inline val Vec4f.ttpp: Vec4f get() = Vec4f(t, t, p, p)
inline val Vec4f.ttpq: Vec4f get() = Vec4f(t, t, p, q)
inline val Vec4f.ttqs: Vec4f get() = Vec4f(t, t, q, s)
inline val Vec4f.ttqt: Vec4f get() = Vec4f(t, t, q, t)
inline val Vec4f.ttqp: Vec4f get() = Vec4f(t, t, q, p)
inline val Vec4f.ttqq: Vec4f get() = Vec4f(t, t, q, q)
inline val Vec4f.tpss: Vec4f get() = Vec4f(t, p, s, s)
inline val Vec4f.tpst: Vec4f get() = Vec4f(t, p, s, t)
inline val Vec4f.tpsp: Vec4f get() = Vec4f(t, p, s, p)
inline val Vec4f.tpts: Vec4f get() = Vec4f(t, p, t, s)
inline val Vec4f.tptt: Vec4f get() = Vec4f(t, p, t, t)
inline val Vec4f.tptp: Vec4f get() = Vec4f(t, p, t, p)
inline val Vec4f.tptq: Vec4f get() = Vec4f(t, p, t, q)
inline val Vec4f.tpps: Vec4f get() = Vec4f(t, p, p, s)
inline val Vec4f.tppt: Vec4f get() = Vec4f(t, p, p, t)
inline val Vec4f.tppp: Vec4f get() = Vec4f(t, p, p, p)
inline val Vec4f.tppq: Vec4f get() = Vec4f(t, p, p, q)
inline val Vec4f.tpqt: Vec4f get() = Vec4f(t, p, q, t)
inline val Vec4f.tpqp: Vec4f get() = Vec4f(t, p, q, p)
inline val Vec4f.tpqq: Vec4f get() = Vec4f(t, p, q, q)
inline val Vec4f.tqss: Vec4f get() = Vec4f(t, q, s, s)
inline val Vec4f.tqst: Vec4f get() = Vec4f(t, q, s, t)
inline val Vec4f.tqsq: Vec4f get() = Vec4f(t, q, s, q)
inline val Vec4f.tqts: Vec4f get() = Vec4f(t, q, t, s)
inline val Vec4f.tqtt: Vec4f get() = Vec4f(t, q, t, t)
inline val Vec4f.tqtp: Vec4f get() = Vec4f(t, q, t, p)
inline val Vec4f.tqtq: Vec4f get() = Vec4f(t, q, t, q)
inline val Vec4f.tqpt: Vec4f get() = Vec4f(t, q, p, t)
inline val Vec4f.tqpp: Vec4f get() = Vec4f(t, q, p, p)
inline val Vec4f.tqpq: Vec4f get() = Vec4f(t, q, p, q)
inline val Vec4f.tqqs: Vec4f get() = Vec4f(t, q, q, s)
inline val Vec4f.tqqt: Vec4f get() = Vec4f(t, q, q, t)
inline val Vec4f.tqqp: Vec4f get() = Vec4f(t, q, q, p)
inline val Vec4f.tqqq: Vec4f get() = Vec4f(t, q, q, q)
inline val Vec4f.psss: Vec4f get() = Vec4f(p, s, s, s)
inline val Vec4f.psst: Vec4f get() = Vec4f(p, s, s, t)
inline val Vec4f.pssp: Vec4f get() = Vec4f(p, s, s, p)
inline val Vec4f.pssq: Vec4f get() = Vec4f(p, s, s, q)
inline val Vec4f.psts: Vec4f get() = Vec4f(p, s, t, s)
inline val Vec4f.pstt: Vec4f get() = Vec4f(p, s, t, t)
inline val Vec4f.pstp: Vec4f get() = Vec4f(p, s, t, p)
inline val Vec4f.psps: Vec4f get() = Vec4f(p, s, p, s)
inline val Vec4f.pspt: Vec4f get() = Vec4f(p, s, p, t)
inline val Vec4f.pspp: Vec4f get() = Vec4f(p, s, p, p)
inline val Vec4f.pspq: Vec4f get() = Vec4f(p, s, p, q)
inline val Vec4f.psqs: Vec4f get() = Vec4f(p, s, q, s)
inline val Vec4f.psqp: Vec4f get() = Vec4f(p, s, q, p)
inline val Vec4f.psqq: Vec4f get() = Vec4f(p, s, q, q)
inline val Vec4f.ptss: Vec4f get() = Vec4f(p, t, s, s)
inline val Vec4f.ptst: Vec4f get() = Vec4f(p, t, s, t)
inline val Vec4f.ptsp: Vec4f get() = Vec4f(p, t, s, p)
inline val Vec4f.ptts: Vec4f get() = Vec4f(p, t, t, s)
inline val Vec4f.pttt: Vec4f get() = Vec4f(p, t, t, t)
inline val Vec4f.pttp: Vec4f get() = Vec4f(p, t, t, p)
inline val Vec4f.pttq: Vec4f get() = Vec4f(p, t, t, q)
inline val Vec4f.ptps: Vec4f get() = Vec4f(p, t, p, s)
inline val Vec4f.ptpt: Vec4f get() = Vec4f(p, t, p, t)
inline val Vec4f.ptpp: Vec4f get() = Vec4f(p, t, p, p)
inline val Vec4f.ptpq: Vec4f get() = Vec4f(p, t, p, q)
inline val Vec4f.ptqt: Vec4f get() = Vec4f(p, t, q, t)
inline val Vec4f.ptqp: Vec4f get() = Vec4f(p, t, q, p)
inline val Vec4f.ptqq: Vec4f get() = Vec4f(p, t, q, q)
inline val Vec4f.ppss: Vec4f get() = Vec4f(p, p, s, s)
inline val Vec4f.ppst: Vec4f get() = Vec4f(p, p, s, t)
inline val Vec4f.ppsp: Vec4f get() = Vec4f(p, p, s, p)
inline val Vec4f.ppsq: Vec4f get() = Vec4f(p, p, s, q)
inline val Vec4f.ppts: Vec4f get() = Vec4f(p, p, t, s)
inline val Vec4f.pptt: Vec4f get() = Vec4f(p, p, t, t)
inline val Vec4f.pptp: Vec4f get() = Vec4f(p, p, t, p)
inline val Vec4f.pptq: Vec4f get() = Vec4f(p, p, t, q)
inline val Vec4f.ppps: Vec4f get() = Vec4f(p, p, p, s)
inline val Vec4f.pppt: Vec4f get() = Vec4f(p, p, p, t)
inline val Vec4f.pppp: Vec4f get() = Vec4f(p, p, p, p)
inline val Vec4f.pppq: Vec4f get() = Vec4f(p, p, p, q)
inline val Vec4f.ppqs: Vec4f get() = Vec4f(p, p, q, s)
inline val Vec4f.ppqt: Vec4f get() = Vec4f(p, p, q, t)
inline val Vec4f.ppqp: Vec4f get() = Vec4f(p, p, q, p)
inline val Vec4f.ppqq: Vec4f get() = Vec4f(p, p, q, q)
inline val Vec4f.pqss: Vec4f get() = Vec4f(p, q, s, s)
inline val Vec4f.pqsp: Vec4f get() = Vec4f(p, q, s, p)
inline val Vec4f.pqsq: Vec4f get() = Vec4f(p, q, s, q)
inline val Vec4f.pqtt: Vec4f get() = Vec4f(p, q, t, t)
inline val Vec4f.pqtp: Vec4f get() = Vec4f(p, q, t, p)
inline val Vec4f.pqtq: Vec4f get() = Vec4f(p, q, t, q)
inline val Vec4f.pqps: Vec4f get() = Vec4f(p, q, p, s)
inline val Vec4f.pqpt: Vec4f get() = Vec4f(p, q, p, t)
inline val Vec4f.pqpp: Vec4f get() = Vec4f(p, q, p, p)
inline val Vec4f.pqpq: Vec4f get() = Vec4f(p, q, p, q)
inline val Vec4f.pqqs: Vec4f get() = Vec4f(p, q, q, s)
inline val Vec4f.pqqt: Vec4f get() = Vec4f(p, q, q, t)
inline val Vec4f.pqqp: Vec4f get() = Vec4f(p, q, q, p)
inline val Vec4f.pqqq: Vec4f get() = Vec4f(p, q, q, q)
inline val Vec4f.qsss: Vec4f get() = Vec4f(q, s, s, s)
inline val Vec4f.qsst: Vec4f get() = Vec4f(q, s, s, t)
inline val Vec4f.qssp: Vec4f get() = Vec4f(q, s, s, p)
inline val Vec4f.qssq: Vec4f get() = Vec4f(q, s, s, q)
inline val Vec4f.qsts: Vec4f get() = Vec4f(q, s, t, s)
inline val Vec4f.qstt: Vec4f get() = Vec4f(q, s, t, t)
inline val Vec4f.qstq: Vec4f get() = Vec4f(q, s, t, q)
inline val Vec4f.qsps: Vec4f get() = Vec4f(q, s, p, s)
inline val Vec4f.qspp: Vec4f get() = Vec4f(q, s, p, p)
inline val Vec4f.qspq: Vec4f get() = Vec4f(q, s, p, q)
inline val Vec4f.qsqs: Vec4f get() = Vec4f(q, s, q, s)
inline val Vec4f.qsqt: Vec4f get() = Vec4f(q, s, q, t)
inline val Vec4f.qsqp: Vec4f get() = Vec4f(q, s, q, p)
inline val Vec4f.qsqq: Vec4f get() = Vec4f(q, s, q, q)
inline val Vec4f.qtss: Vec4f get() = Vec4f(q, t, s, s)
inline val Vec4f.qtst: Vec4f get() = Vec4f(q, t, s, t)
inline val Vec4f.qtsq: Vec4f get() = Vec4f(q, t, s, q)
inline val Vec4f.qtts: Vec4f get() = Vec4f(q, t, t, s)
inline val Vec4f.qttt: Vec4f get() = Vec4f(q, t, t, t)
inline val Vec4f.qttp: Vec4f get() = Vec4f(q, t, t, p)
inline val Vec4f.qttq: Vec4f get() = Vec4f(q, t, t, q)
inline val Vec4f.qtpt: Vec4f get() = Vec4f(q, t, p, t)
inline val Vec4f.qtpp: Vec4f get() = Vec4f(q, t, p, p)
inline val Vec4f.qtpq: Vec4f get() = Vec4f(q, t, p, q)
inline val Vec4f.qtqs: Vec4f get() = Vec4f(q, t, q, s)
inline val Vec4f.qtqt: Vec4f get() = Vec4f(q, t, q, t)
inline val Vec4f.qtqp: Vec4f get() = Vec4f(q, t, q, p)
inline val Vec4f.qtqq: Vec4f get() = Vec4f(q, t, q, q)
inline val Vec4f.qpss: Vec4f get() = Vec4f(q, p, s, s)
inline val Vec4f.qpsp: Vec4f get() = Vec4f(q, p, s, p)
inline val Vec4f.qpsq: Vec4f get() = Vec4f(q, p, s, q)
inline val Vec4f.qptt: Vec4f get() = Vec4f(q, p, t, t)
inline val Vec4f.qptp: Vec4f get() = Vec4f(q, p, t, p)
inline val Vec4f.qptq: Vec4f get() = Vec4f(q, p, t, q)
inline val Vec4f.qpps: Vec4f get() = Vec4f(q, p, p, s)
inline val Vec4f.qppt: Vec4f get() = Vec4f(q, p, p, t)
inline val Vec4f.qppp: Vec4f get() = Vec4f(q, p, p, p)
inline val Vec4f.qppq: Vec4f get() = Vec4f(q, p, p, q)
inline val Vec4f.qpqs: Vec4f get() = Vec4f(q, p, q, s)
inline val Vec4f.qpqt: Vec4f get() = Vec4f(q, p, q, t)
inline val Vec4f.qpqp: Vec4f get() = Vec4f(q, p, q, p)
inline val Vec4f.qpqq: Vec4f get() = Vec4f(q, p, q, q)
inline val Vec4f.qqss: Vec4f get() = Vec4f(q, q, s, s)
inline val Vec4f.qqst: Vec4f get() = Vec4f(q, q, s, t)
inline val Vec4f.qqsp: Vec4f get() = Vec4f(q, q, s, p)
inline val Vec4f.qqsq: Vec4f get() = Vec4f(q, q, s, q)
inline val Vec4f.qqts: Vec4f get() = Vec4f(q, q, t, s)
inline val Vec4f.qqtt: Vec4f get() = Vec4f(q, q, t, t)
inline val Vec4f.qqtp: Vec4f get() = Vec4f(q, q, t, p)
inline val Vec4f.qqtq: Vec4f get() = Vec4f(q, q, t, q)
inline val Vec4f.qqps: Vec4f get() = Vec4f(q, q, p, s)
inline val Vec4f.qqpt: Vec4f get() = Vec4f(q, q, p, t)
inline val Vec4f.qqpp: Vec4f get() = Vec4f(q, q, p, p)
inline val Vec4f.qqpq: Vec4f get() = Vec4f(q, q, p, q)
inline val Vec4f.qqqs: Vec4f get() = Vec4f(q, q, q, s)
inline val Vec4f.qqqt: Vec4f get() = Vec4f(q, q, q, t)
inline val Vec4f.qqqp: Vec4f get() = Vec4f(q, q, q, p)
inline val Vec4f.qqqq: Vec4f get() = Vec4f(q, q, q, q)
